<?php
/**
 * CampaignTest
 *
 * PHP version 7
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

// namespace NecLimDul\MarketoRest\Lead;
namespace NecLimDul\MarketoRest\Lead\Model;

use PHPUnit\Framework\TestCase;

/**
 * CampaignTest Class Doc Comment
 *
 * @category    Class
 * @description Record of a Marketo Smart Campaign
 * @package     NecLimDul\MarketoRest\Lead
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTest extends TestCase
{

    /**
     * Test "Campaign"
     */
    public function testCampaign()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "program_id"
     */
    public function testPropertyProgramId()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "program_name"
     */
    public function testPropertyProgramName()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "workspace_name"
     */
    public function testPropertyWorkspaceName()
    {
        $class = new Campaign();
        $this->assertTrue(TRUE);
    }
}
