<?php
/**
 * LeadAttribute2SearchableFieldsTest
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace NecLimDul\MarketoRest\Lead\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LeadAttribute2SearchableFieldsTest Class Doc Comment
 *
 * @category    Class
 * @description List of searchable fields
 * @package     NecLimDul\MarketoRest\Lead
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadAttribute2SearchableFieldsTest extends TestCase
{

    /**
     * Test "LeadAttribute2SearchableFields"
     */
    public function testLeadAttribute2SearchableFields()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
