<?php

/**
 * ModelListTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Lead\Test\Model;

use Faker\Factory as FakerFactory;
use NecLimDul\MarketoRest\Lead\Model\ModelInterface;
use NecLimDul\MarketoRest\Lead\Model\ModelList;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * ModelListTest
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.21.0
 */
#[CoversClass(ModelList::class)]
class ModelListTest extends TestCase
{
    use FakeValuesTrait;

    private ModelList $sot;

    /**
     * @var string[]
     */
    private array $types = [
        'created_at' => 'string',
        'list_id' => 'int',
        'updated_at' => 'string',
    ];

    /**
     * @var scalar[][]
     */
    private array $allowedValues = [
    ];

    public function setUp(): void
    {
        parent::setUp();
        $this->setFaker(FakerFactory::create());
        $this->sot = $this->getFakeValue(ModelList::class, null);
    }

    /**
     * Test "ModelList"
     *
     * @legacy-covers ::__construct
     */
    public function testModelList(): void
    {
        $this->assertInstanceOf(ModelList::class, $this->sot);
    }

    /**
     * @legacy-covers ::openAPITypes
     */
    public function testOpenApiTypes(): void
    {
        $this->assertEquals($this->types, ModelList::openAPITypes());
    }

    /**
     * @legacy-covers ::openAPIRequired
     */
    public function testOpenAPIRequired(): void
    {
        $required = $this->sot->openAPIRequired();
        $this->assertEquals('created_at', $required['created_at']);
        $this->assertEquals('list_id', $required['list_id']);
        $this->assertEquals('updated_at', $required['updated_at']);
    }

    /**
     * @legacy-covers ::openAPIFormats
     */
    public function testOpenAPIFormats(): void
    {
        $formats = $this->sot->openAPIFormats();
        $this->assertNotContains('created_at', $formats);
        $this->assertEquals('int32', $formats['list_id']);
        $this->assertNotContains('updated_at', $formats);
    }

    /**
     * @legacy-covers ::attributeMap
     */
    public function testAttributeMap(): void
    {
        $attributes = $this->sot->attributeMap();
        $this->assertEquals('createdAt', $attributes['created_at']);
        $this->assertEquals('listId', $attributes['list_id']);
        $this->assertEquals('updatedAt', $attributes['updated_at']);
    }

    /**
     * @legacy-covers ::getters
     * @legacy-covers ::setters
     */
    public function testGettersSetters(): void
    {
        $getters = $this->sot->getters();
        $setters = $this->sot->setters();
        foreach (array_keys($this->types) as $field) {
            $this->assertTrue(isset($setters[$field]));
            $this->assertTrue(isset($getters[$field]));
        }
    }

    /**
     * @legacy-covers ::getModelName
     */
    public function testGetModelName(): void
    {
        $this->assertEquals('List', $this->sot->getModelName());
    }

    /**
     * @legacy-covers ::setAdditionalProperties
     * @legacy-covers ::setAdditionalProperty
     * @legacy-covers ::getAdditionalProperties
     */
    public function testAdditionalProperties(): void
    {
        do {
            $property = $this->faker->word();
        } while (isset($this->sot::attributeMap()[$property]));
        $value = 'foobar';
        $this->sot[$property] = $value;
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperty($property, $value);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperties([
            $property => $value,
        ]);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        $this->assertEquals(
            $value,
            $this->sot->jsonSerialize()->$property
        );
    }

    /**
     * @legacy-covers ::setAdditionalProperty
     */
    public function testAdditionalPropertyExistingProperty(): void
    {
        $this->expectException(\AssertionError::class);
        $this->sot->setAdditionalProperty(key($this->sot::attributeMap()), 'foobar');
    }

    /**
     * @legacy-covers ::jsonSerialize
     * @legacy-covers ::__toString
     */
    public function testJson(): void
    {
        // Some minimal tests that json generates well.
        $json = json_encode($this->sot);
        $this->assertIsString($json, 'Json encoded');
        $json = json_decode($json);
        $string = json_decode((string) $this->sot);
        $this->assertEquals(
            $json,
            $string
        );
        $this->assertInstanceOf(\stdClass::class, $json);
        $this->assertInstanceOf(\stdClass::class, $string);
    }

    /**
     * Test attribute "created_at"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getCreatedAt
     * @legacy-covers ::setCreatedAt
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyCreatedAt(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['created_at'],
            $this->allowedValues['created_at'] ?? null
        );
        $this->sot->setCreatedAt($v);
        $this->assertEquals($v, $this->sot->getCreatedAt());

        $this->assertEquals($v, $this->sot['created_at']);
        $v = $this->getFakeValue(
            $this->types['created_at'],
            $this->allowedValues['created_at'] ?? null
        );
        $this->sot['created_at'] = $v;
        $this->assertTrue(isset($this->sot['created_at']));
        $this->assertEquals($v, $this->sot['created_at']);
        $this->assertEquals($v, $this->sot->getCreatedAt());
        unset($this->sot['created_at']);
        $this->assertFalse(isset($this->sot['created_at']));
        $this->sot['created_at'] = $v;
        $this->assertEquals($v, $this->sot['created_at']);
        $this->assertTrue(isset($this->sot['created_at']));
        $this->sot['created_at'] = null;
        $this->assertFalse(isset($this->sot['created_at']));
    }

    /**
     * Test attribute "list_id"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getListId
     * @legacy-covers ::setListId
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyListId(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['list_id'],
            $this->allowedValues['list_id'] ?? null
        );
        $this->sot->setListId($v);
        $this->assertEquals($v, $this->sot->getListId());

        $this->assertEquals($v, $this->sot['list_id']);
        $v = $this->getFakeValue(
            $this->types['list_id'],
            $this->allowedValues['list_id'] ?? null
        );
        $this->sot['list_id'] = $v;
        $this->assertTrue(isset($this->sot['list_id']));
        $this->assertEquals($v, $this->sot['list_id']);
        $this->assertEquals($v, $this->sot->getListId());
        unset($this->sot['list_id']);
        $this->assertFalse(isset($this->sot['list_id']));
        $this->sot['list_id'] = $v;
        $this->assertEquals($v, $this->sot['list_id']);
        $this->assertTrue(isset($this->sot['list_id']));
        $this->sot['list_id'] = null;
        $this->assertFalse(isset($this->sot['list_id']));
    }

    /**
     * Test attribute "updated_at"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getUpdatedAt
     * @legacy-covers ::setUpdatedAt
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyUpdatedAt(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['updated_at'],
            $this->allowedValues['updated_at'] ?? null
        );
        $this->sot->setUpdatedAt($v);
        $this->assertEquals($v, $this->sot->getUpdatedAt());

        $this->assertEquals($v, $this->sot['updated_at']);
        $v = $this->getFakeValue(
            $this->types['updated_at'],
            $this->allowedValues['updated_at'] ?? null
        );
        $this->sot['updated_at'] = $v;
        $this->assertTrue(isset($this->sot['updated_at']));
        $this->assertEquals($v, $this->sot['updated_at']);
        $this->assertEquals($v, $this->sot->getUpdatedAt());
        unset($this->sot['updated_at']);
        $this->assertFalse(isset($this->sot['updated_at']));
        $this->sot['updated_at'] = $v;
        $this->assertEquals($v, $this->sot['updated_at']);
        $this->assertTrue(isset($this->sot['updated_at']));
        $this->sot['updated_at'] = null;
        $this->assertFalse(isset($this->sot['updated_at']));
    }

    /**
     * Test invalid use of offsetSet.
     *
     * @legacy-covers ::offsetSet
     */
    public function testInvalidOffsetException(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->sot[] = 'foobar';
    }
}
