<?php
/**
 * ScheduleCampaignDataTest
 *
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace NecLimDul\MarketoRest\Lead\Test\Model;

use Faker\Factory;
use NecLimDul\MarketoRest\Lead\Model\ModelInterface;
use NecLimDul\MarketoRest\Lead\Model\ScheduleCampaignData;
use PHPUnit\Framework\TestCase;

/**
 * ScheduleCampaignDataTest Class Doc Comment
 *
 * @category    Class
 * @description ScheduleCampaignData
 * @package     NecLimDul\MarketoRest\Lead
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 *
 * @coversDefaultClass \NecLimDul\MarketoRest\Lead\Model\ScheduleCampaignData
 */
class ScheduleCampaignDataTest extends TestCase
{

    /**
     * @var \NecLimDul\MarketoRest\Lead\Model\ScheduleCampaignData
     */
    private $sot;

    /**
     * @var string[]
     */
    private $types = [
        'clone_to_program_name' => 'string',
        'run_at' => '\DateTime',
        'tokens' => '\NecLimDul\MarketoRest\Lead\Model\Token[]',
];

    /**
     * @var \Faker\Generator
     */
    private $faker;

    /**
     * @var scalar[][]
     */
    private $allowedValues = [
    ];

    public function setUp(): void
    {
        parent::setUp();
        $this->faker = \Faker\Factory::create();
        $data = [];
        foreach ($this->types as $field => $type) {
            $data[$field] = $this->getFakeValue($type, $this->allowedValues[$field] ?? null);
        }
        $this->sot = new ScheduleCampaignData($data);
    }

    /**
     * @param string $type
     * @param scalar[]|null $values
     * @return mixed
     */
    private function getFakeValue(string $type, ?array $values) {
        if (isset($values)) {
            // @todo random.
            return array_pop($values);
        }

        // @todo look for container hints.
        if (strcasecmp(substr($type, -2), '[]') === 0) {
            $return = [];
            $subType = substr($type, 0, -2);
            for ($i = 0; $i <= rand(0, 9); $i++) {
                $return[] = $this->getFakeValue($subType, $values);
            }
            return $return;
        }
        switch ($type) {
            case 'string':
                return $this->faker->word();
            case 'float':
                return $this->faker->randomFloat();
            case 'int':
                return $this->faker->randomNumber();
            case 'bool':
                return $this->faker->boolean();
            case '\DateTime':
                return $this->faker->dateTimeAD();
            case 'object':
                return new \stdClass();
        }
        if (class_exists($type) && is_subclass_of($type, ModelInterface::class)) {
            $model = new $type();
            $types = $type::swaggerTypes();
            foreach ($model->listInvalidProperties() as $field => $reason) {
                // @todo get allowed values? ((getter))AllowedValues
                // @phpstan-ignore-next-line
                $model[$field] = $this->getFakeValue($types[$field], null);
            }
            return $model;
        }
        $this->markTestSkipped('This type is not mocked yet: ' . $type);
    }

    /**
     * Test "ScheduleCampaignData"
     *
     * @covers ::__construct
     */
    public function testScheduleCampaignData(): void
    {
        $this->assertInstanceOf(ScheduleCampaignData::class, $this->sot);
    }

    /**
     * @covers ::swaggerTypes
     */
    public function testSwaggerTypes(): void
    {
        $this->assertEquals($this->types, ScheduleCampaignData::swaggerTypes());
    }

    /**
     * @covers ::swaggerFormats
     */
    public function testSwaggerFormats(): void
    {
        $formats = $this->sot->swaggerFormats();
        $this->assertEquals(null, $formats['clone_to_program_name']);
        $this->assertEquals('date-time', $formats['run_at']);
        $this->assertEquals(null, $formats['tokens']);
    }

    /**
     * @covers ::attributeMap
     */
    public function testAttributeMap(): void
    {
        $formats = $this->sot->attributeMap();
        $this->assertEquals('cloneToProgramName', $formats['clone_to_program_name']);
        $this->assertEquals('runAt', $formats['run_at']);
        $this->assertEquals('tokens', $formats['tokens']);
    }

    /**
     * @covers ::getters
     * @covers ::setters
     */
    public function testGettersSetters(): void
    {
        $getters = $this->sot->getters();
        $setters = $this->sot->setters();
        foreach (array_keys($this->types) as $field) {
            $this->assertTrue(isset($setters[$field]));
            $this->assertTrue(isset($getters[$field]));
            $this->assertTrue(
                method_exists($this->sot, $getters[$field]),
                'Getter exists on model.'
            );
            $this->assertTrue(
                method_exists($this->sot, $setters[$field]),
                'Setter exists on model.'
            );
        }
    }

    /**
     * @covers ::getModelName
     */
    public function testGetModelName(): void
    {
        $this->assertEquals('ScheduleCampaignData', $this->sot->getModelName());
    }

    /**
     * @covers ::listInvalidProperties
     * @covers ::valid
     */
    public function testValid(): void
    {
        $this->markTestIncomplete('TODO');
    }

    /**
     * @covers ::setAdditionalProperties
     * @covers ::setAdditionalProperty
     * @covers ::getAdditionalProperties
     */
    public function testAdditionalProperties(): void
    {
        $this->markTestIncomplete('TODO');
    }

    /**
     * @covers ::jsonSerialize
     * @covers ::__toString
     */
    public function testJson(): void
    {
        // Some minimal tests that json generates well.
        $json = json_encode($this->sot);
        $this->assertIsString($json, 'Json encoded');
        $json = json_decode($json);
        $string = json_decode((string) $this->sot);
        $this->assertEquals(
            $json,
            $string
        );
        $this->assertInstanceOf(\stdClass::class, $json);
        $this->assertInstanceOf(\stdClass::class, $string);
    }

    /**
     * Test attribute "clone_to_program_name"
     *
     * @covers ::__construct
     * @covers ::getCloneToProgramName
     * @covers ::setCloneToProgramName
     * @covers ::offsetExists
     * @covers ::offsetGet
     * @covers ::offsetSet
     * @covers ::offsetUnset
     */
    public function testPropertyCloneToProgramName(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['clone_to_program_name'],
            $this->allowedValues['clone_to_program_name'] ?? null
        );
        $this->sot->setCloneToProgramName($v);
        $this->assertEquals($v, $this->sot->getCloneToProgramName());
        $this->sot->setCloneToProgramName(null);
        $this->assertNull($this->sot->getCloneToProgramName());
        $this->sot->setCloneToProgramName($v);

        $this->assertEquals($v, $this->sot['clone_to_program_name']);
        $v = $this->getFakeValue(
            $this->types['clone_to_program_name'],
            $this->allowedValues['clone_to_program_name'] ?? null
        );
        $this->sot['clone_to_program_name'] = $v;
        $this->assertEquals($v, $this->sot['clone_to_program_name']);
        $this->assertTrue(isset($this->sot['clone_to_program_name']));
        unset($this->sot['clone_to_program_name']);
        $this->assertFalse(isset($this->sot['clone_to_program_name']));
        $this->sot['clone_to_program_name'] = $v;
        $this->assertEquals($v, $this->sot['clone_to_program_name']);
        $this->assertTrue(isset($this->sot['clone_to_program_name']));
    }

    /**
     * Test attribute "run_at"
     *
     * @covers ::__construct
     * @covers ::getRunAt
     * @covers ::setRunAt
     * @covers ::offsetExists
     * @covers ::offsetGet
     * @covers ::offsetSet
     * @covers ::offsetUnset
     */
    public function testPropertyRunAt(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['run_at'],
            $this->allowedValues['run_at'] ?? null
        );
        $this->sot->setRunAt($v);
        $this->assertEquals($v, $this->sot->getRunAt());
        $this->sot->setRunAt(null);
        $this->assertNull($this->sot->getRunAt());
        $this->sot->setRunAt($v);

        $this->assertEquals($v, $this->sot['run_at']);
        $v = $this->getFakeValue(
            $this->types['run_at'],
            $this->allowedValues['run_at'] ?? null
        );
        $this->sot['run_at'] = $v;
        $this->assertEquals($v, $this->sot['run_at']);
        $this->assertTrue(isset($this->sot['run_at']));
        unset($this->sot['run_at']);
        $this->assertFalse(isset($this->sot['run_at']));
        $this->sot['run_at'] = $v;
        $this->assertEquals($v, $this->sot['run_at']);
        $this->assertTrue(isset($this->sot['run_at']));
    }

    /**
     * Test attribute "tokens"
     *
     * @covers ::__construct
     * @covers ::getTokens
     * @covers ::setTokens
     * @covers ::offsetExists
     * @covers ::offsetGet
     * @covers ::offsetSet
     * @covers ::offsetUnset
     */
    public function testPropertyTokens(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['tokens'],
            $this->allowedValues['tokens'] ?? null
        );
        $this->sot->setTokens($v);
        $this->assertEquals($v, $this->sot->getTokens());
        $this->sot->setTokens(null);
        $this->assertNull($this->sot->getTokens());
        $this->sot->setTokens($v);

        $this->assertEquals($v, $this->sot['tokens']);
        $v = $this->getFakeValue(
            $this->types['tokens'],
            $this->allowedValues['tokens'] ?? null
        );
        $this->sot['tokens'] = $v;
        $this->assertEquals($v, $this->sot['tokens']);
        $this->assertTrue(isset($this->sot['tokens']));
        unset($this->sot['tokens']);
        $this->assertFalse(isset($this->sot['tokens']));
        $this->sot['tokens'] = $v;
        $this->assertEquals($v, $this->sot['tokens']);
        $this->assertTrue(isset($this->sot['tokens']));
    }
}
