<?php

/**
 * AddFormFieldRequestTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Test\Model;

use Faker\Factory as FakerFactory;
use NecLimDul\MarketoRest\Asset\Model\ModelInterface;
use NecLimDul\MarketoRest\Asset\Model\AddFormFieldRequest;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * AddFormFieldRequestTest
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.21.0
 */
#[CoversClass(AddFormFieldRequest::class)]
class AddFormFieldRequestTest extends TestCase
{
    use FakeValuesTrait;

    private AddFormFieldRequest $sot;

    /**
     * @var string[]
     */
    private array $types = [
        'blank_fields' => 'int',
        'default_value' => 'string',
        'field_id' => 'string',
        'field_type' => 'string',
        'field_width' => 'int',
        'form_prefill' => 'bool',
        'is_sensitive' => 'bool',
        'hint_text' => 'string',
        'initially_checked' => 'bool',
        'instructions' => 'string',
        'label' => 'string',
        'label_to_right' => 'bool',
        'label_width' => 'int',
        'mask_input' => 'string',
        'max_length' => 'int',
        'max_value' => 'float',
        'min_value' => 'float',
        'multi_select' => 'bool',
        'required' => 'bool',
        'validation_message' => 'string',
        'values' => 'string',
        'visible_lines' => 'int',
    ];

    /**
     * @var scalar[][]
     */
    private array $allowedValues = [
    ];

    public function setUp(): void
    {
        parent::setUp();
        $this->setFaker(FakerFactory::create());
        $this->sot = $this->getFakeValue(AddFormFieldRequest::class, null);
    }

    /**
     * Test "AddFormFieldRequest"
     *
     * @legacy-covers ::__construct
     */
    public function testAddFormFieldRequest(): void
    {
        $this->assertInstanceOf(AddFormFieldRequest::class, $this->sot);
    }

    /**
     * @legacy-covers ::openAPITypes
     */
    public function testOpenApiTypes(): void
    {
        $this->assertEquals($this->types, AddFormFieldRequest::openAPITypes());
    }

    /**
     * @legacy-covers ::openAPIRequired
     */
    public function testOpenAPIRequired(): void
    {
        $required = $this->sot->openAPIRequired();
        $this->assertNotContains('blank_fields', $required);
        $this->assertNotContains('default_value', $required);
        $this->assertEquals('field_id', $required['field_id']);
        $this->assertNotContains('field_type', $required);
        $this->assertNotContains('field_width', $required);
        $this->assertNotContains('form_prefill', $required);
        $this->assertNotContains('is_sensitive', $required);
        $this->assertNotContains('hint_text', $required);
        $this->assertNotContains('initially_checked', $required);
        $this->assertNotContains('instructions', $required);
        $this->assertNotContains('label', $required);
        $this->assertNotContains('label_to_right', $required);
        $this->assertNotContains('label_width', $required);
        $this->assertNotContains('mask_input', $required);
        $this->assertNotContains('max_length', $required);
        $this->assertNotContains('max_value', $required);
        $this->assertNotContains('min_value', $required);
        $this->assertNotContains('multi_select', $required);
        $this->assertNotContains('required', $required);
        $this->assertNotContains('validation_message', $required);
        $this->assertNotContains('values', $required);
        $this->assertNotContains('visible_lines', $required);
    }

    /**
     * @legacy-covers ::openAPIFormats
     */
    public function testOpenAPIFormats(): void
    {
        $formats = $this->sot->openAPIFormats();
        $this->assertEquals('int32', $formats['blank_fields']);
        $this->assertNotContains('default_value', $formats);
        $this->assertNotContains('field_id', $formats);
        $this->assertNotContains('field_type', $formats);
        $this->assertEquals('int32', $formats['field_width']);
        $this->assertNotContains('form_prefill', $formats);
        $this->assertNotContains('is_sensitive', $formats);
        $this->assertNotContains('hint_text', $formats);
        $this->assertNotContains('initially_checked', $formats);
        $this->assertNotContains('instructions', $formats);
        $this->assertNotContains('label', $formats);
        $this->assertNotContains('label_to_right', $formats);
        $this->assertEquals('int32', $formats['label_width']);
        $this->assertNotContains('mask_input', $formats);
        $this->assertEquals('int32', $formats['max_length']);
        $this->assertEquals('float', $formats['max_value']);
        $this->assertEquals('float', $formats['min_value']);
        $this->assertNotContains('multi_select', $formats);
        $this->assertNotContains('required', $formats);
        $this->assertNotContains('validation_message', $formats);
        $this->assertNotContains('values', $formats);
        $this->assertEquals('int32', $formats['visible_lines']);
    }

    /**
     * @legacy-covers ::attributeMap
     */
    public function testAttributeMap(): void
    {
        $attributes = $this->sot->attributeMap();
        $this->assertEquals('blankFields', $attributes['blank_fields']);
        $this->assertEquals('defaultValue', $attributes['default_value']);
        $this->assertEquals('fieldId', $attributes['field_id']);
        $this->assertEquals('fieldType', $attributes['field_type']);
        $this->assertEquals('fieldWidth', $attributes['field_width']);
        $this->assertEquals('formPrefill', $attributes['form_prefill']);
        $this->assertEquals('isSensitive', $attributes['is_sensitive']);
        $this->assertEquals('hintText', $attributes['hint_text']);
        $this->assertEquals('initiallyChecked', $attributes['initially_checked']);
        $this->assertEquals('instructions', $attributes['instructions']);
        $this->assertEquals('label', $attributes['label']);
        $this->assertEquals('labelToRight', $attributes['label_to_right']);
        $this->assertEquals('labelWidth', $attributes['label_width']);
        $this->assertEquals('maskInput', $attributes['mask_input']);
        $this->assertEquals('maxLength', $attributes['max_length']);
        $this->assertEquals('maxValue', $attributes['max_value']);
        $this->assertEquals('minValue', $attributes['min_value']);
        $this->assertEquals('multiSelect', $attributes['multi_select']);
        $this->assertEquals('required', $attributes['required']);
        $this->assertEquals('validationMessage', $attributes['validation_message']);
        $this->assertEquals('values', $attributes['values']);
        $this->assertEquals('visibleLines', $attributes['visible_lines']);
    }

    /**
     * @legacy-covers ::getters
     * @legacy-covers ::setters
     */
    public function testGettersSetters(): void
    {
        $getters = $this->sot->getters();
        $setters = $this->sot->setters();
        foreach (array_keys($this->types) as $field) {
            $this->assertTrue(isset($setters[$field]));
            $this->assertTrue(isset($getters[$field]));
        }
    }

    /**
     * @legacy-covers ::getModelName
     */
    public function testGetModelName(): void
    {
        $this->assertEquals('AddFormFieldRequest', $this->sot->getModelName());
    }

    /**
     * @legacy-covers ::setAdditionalProperties
     * @legacy-covers ::setAdditionalProperty
     * @legacy-covers ::getAdditionalProperties
     */
    public function testAdditionalProperties(): void
    {
        do {
            $property = $this->faker->word();
        } while (isset($this->sot::attributeMap()[$property]));
        $value = 'foobar';
        $this->sot[$property] = $value;
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperty($property, $value);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperties([
            $property => $value,
        ]);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        $this->assertEquals(
            $value,
            $this->sot->jsonSerialize()->$property
        );
    }

    /**
     * @legacy-covers ::setAdditionalProperty
     */
    public function testAdditionalPropertyExistingProperty(): void
    {
        $this->expectException(\AssertionError::class);
        $this->sot->setAdditionalProperty(key($this->sot::attributeMap()), 'foobar');
    }

    /**
     * @legacy-covers ::jsonSerialize
     * @legacy-covers ::__toString
     */
    public function testJson(): void
    {
        // Some minimal tests that json generates well.
        $json = json_encode($this->sot);
        $this->assertIsString($json, 'Json encoded');
        $json = json_decode($json);
        $string = json_decode((string) $this->sot);
        $this->assertEquals(
            $json,
            $string
        );
        $this->assertInstanceOf(\stdClass::class, $json);
        $this->assertInstanceOf(\stdClass::class, $string);
    }

    /**
     * Test attribute "blank_fields"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getBlankFields
     * @legacy-covers ::setBlankFields
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyBlankFields(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['blank_fields'],
            $this->allowedValues['blank_fields'] ?? null
        );
        $this->sot->setBlankFields($v);
        $this->assertEquals($v, $this->sot->getBlankFields());
        $this->sot->setBlankFields(null);
        $this->assertNull($this->sot->getBlankFields());
        $this->sot->setBlankFields($v);

        $this->assertEquals($v, $this->sot['blank_fields']);
        $v = $this->getFakeValue(
            $this->types['blank_fields'],
            $this->allowedValues['blank_fields'] ?? null
        );
        $this->sot['blank_fields'] = $v;
        $this->assertTrue(isset($this->sot['blank_fields']));
        $this->assertEquals($v, $this->sot['blank_fields']);
        $this->assertEquals($v, $this->sot->getBlankFields());
        unset($this->sot['blank_fields']);
        $this->assertFalse(isset($this->sot['blank_fields']));
        $this->sot['blank_fields'] = $v;
        $this->assertEquals($v, $this->sot['blank_fields']);
        $this->assertTrue(isset($this->sot['blank_fields']));
        $this->sot['blank_fields'] = null;
        $this->assertFalse(isset($this->sot['blank_fields']));
    }

    /**
     * Test attribute "default_value"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getDefaultValue
     * @legacy-covers ::setDefaultValue
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyDefaultValue(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['default_value'],
            $this->allowedValues['default_value'] ?? null
        );
        $this->sot->setDefaultValue($v);
        $this->assertEquals($v, $this->sot->getDefaultValue());
        $this->sot->setDefaultValue(null);
        $this->assertNull($this->sot->getDefaultValue());
        $this->sot->setDefaultValue($v);

        $this->assertEquals($v, $this->sot['default_value']);
        $v = $this->getFakeValue(
            $this->types['default_value'],
            $this->allowedValues['default_value'] ?? null
        );
        $this->sot['default_value'] = $v;
        $this->assertTrue(isset($this->sot['default_value']));
        $this->assertEquals($v, $this->sot['default_value']);
        $this->assertEquals($v, $this->sot->getDefaultValue());
        unset($this->sot['default_value']);
        $this->assertFalse(isset($this->sot['default_value']));
        $this->sot['default_value'] = $v;
        $this->assertEquals($v, $this->sot['default_value']);
        $this->assertTrue(isset($this->sot['default_value']));
        $this->sot['default_value'] = null;
        $this->assertFalse(isset($this->sot['default_value']));
    }

    /**
     * Test attribute "field_id"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getFieldId
     * @legacy-covers ::setFieldId
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyFieldId(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['field_id'],
            $this->allowedValues['field_id'] ?? null
        );
        $this->sot->setFieldId($v);
        $this->assertEquals($v, $this->sot->getFieldId());

        $this->assertEquals($v, $this->sot['field_id']);
        $v = $this->getFakeValue(
            $this->types['field_id'],
            $this->allowedValues['field_id'] ?? null
        );
        $this->sot['field_id'] = $v;
        $this->assertTrue(isset($this->sot['field_id']));
        $this->assertEquals($v, $this->sot['field_id']);
        $this->assertEquals($v, $this->sot->getFieldId());
        unset($this->sot['field_id']);
        $this->assertFalse(isset($this->sot['field_id']));
        $this->sot['field_id'] = $v;
        $this->assertEquals($v, $this->sot['field_id']);
        $this->assertTrue(isset($this->sot['field_id']));
        $this->sot['field_id'] = null;
        $this->assertFalse(isset($this->sot['field_id']));
    }

    /**
     * Test attribute "field_type"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getFieldType
     * @legacy-covers ::setFieldType
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyFieldType(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['field_type'],
            $this->allowedValues['field_type'] ?? null
        );
        $this->sot->setFieldType($v);
        $this->assertEquals($v, $this->sot->getFieldType());
        $this->sot->setFieldType(null);
        $this->assertNull($this->sot->getFieldType());
        $this->sot->setFieldType($v);

        $this->assertEquals($v, $this->sot['field_type']);
        $v = $this->getFakeValue(
            $this->types['field_type'],
            $this->allowedValues['field_type'] ?? null
        );
        $this->sot['field_type'] = $v;
        $this->assertTrue(isset($this->sot['field_type']));
        $this->assertEquals($v, $this->sot['field_type']);
        $this->assertEquals($v, $this->sot->getFieldType());
        unset($this->sot['field_type']);
        $this->assertFalse(isset($this->sot['field_type']));
        $this->sot['field_type'] = $v;
        $this->assertEquals($v, $this->sot['field_type']);
        $this->assertTrue(isset($this->sot['field_type']));
        $this->sot['field_type'] = null;
        $this->assertFalse(isset($this->sot['field_type']));
    }

    /**
     * Test attribute "field_width"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getFieldWidth
     * @legacy-covers ::setFieldWidth
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyFieldWidth(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['field_width'],
            $this->allowedValues['field_width'] ?? null
        );
        $this->sot->setFieldWidth($v);
        $this->assertEquals($v, $this->sot->getFieldWidth());
        $this->sot->setFieldWidth(null);
        $this->assertNull($this->sot->getFieldWidth());
        $this->sot->setFieldWidth($v);

        $this->assertEquals($v, $this->sot['field_width']);
        $v = $this->getFakeValue(
            $this->types['field_width'],
            $this->allowedValues['field_width'] ?? null
        );
        $this->sot['field_width'] = $v;
        $this->assertTrue(isset($this->sot['field_width']));
        $this->assertEquals($v, $this->sot['field_width']);
        $this->assertEquals($v, $this->sot->getFieldWidth());
        unset($this->sot['field_width']);
        $this->assertFalse(isset($this->sot['field_width']));
        $this->sot['field_width'] = $v;
        $this->assertEquals($v, $this->sot['field_width']);
        $this->assertTrue(isset($this->sot['field_width']));
        $this->sot['field_width'] = null;
        $this->assertFalse(isset($this->sot['field_width']));
    }

    /**
     * Test attribute "form_prefill"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getFormPrefill
     * @legacy-covers ::setFormPrefill
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyFormPrefill(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['form_prefill'],
            $this->allowedValues['form_prefill'] ?? null
        );
        $this->sot->setFormPrefill($v);
        $this->assertEquals($v, $this->sot->getFormPrefill());
        $this->sot->setFormPrefill(null);
        $this->assertNull($this->sot->getFormPrefill());
        $this->sot->setFormPrefill($v);

        $this->assertEquals($v, $this->sot['form_prefill']);
        $v = $this->getFakeValue(
            $this->types['form_prefill'],
            $this->allowedValues['form_prefill'] ?? null
        );
        $this->sot['form_prefill'] = $v;
        $this->assertTrue(isset($this->sot['form_prefill']));
        $this->assertEquals($v, $this->sot['form_prefill']);
        $this->assertEquals($v, $this->sot->getFormPrefill());
        unset($this->sot['form_prefill']);
        $this->assertFalse(isset($this->sot['form_prefill']));
        $this->sot['form_prefill'] = $v;
        $this->assertEquals($v, $this->sot['form_prefill']);
        $this->assertTrue(isset($this->sot['form_prefill']));
        $this->sot['form_prefill'] = null;
        $this->assertFalse(isset($this->sot['form_prefill']));
    }

    /**
     * Test attribute "is_sensitive"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getIsSensitive
     * @legacy-covers ::setIsSensitive
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyIsSensitive(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['is_sensitive'],
            $this->allowedValues['is_sensitive'] ?? null
        );
        $this->sot->setIsSensitive($v);
        $this->assertEquals($v, $this->sot->getIsSensitive());
        $this->sot->setIsSensitive(null);
        $this->assertNull($this->sot->getIsSensitive());
        $this->sot->setIsSensitive($v);

        $this->assertEquals($v, $this->sot['is_sensitive']);
        $v = $this->getFakeValue(
            $this->types['is_sensitive'],
            $this->allowedValues['is_sensitive'] ?? null
        );
        $this->sot['is_sensitive'] = $v;
        $this->assertTrue(isset($this->sot['is_sensitive']));
        $this->assertEquals($v, $this->sot['is_sensitive']);
        $this->assertEquals($v, $this->sot->getIsSensitive());
        unset($this->sot['is_sensitive']);
        $this->assertFalse(isset($this->sot['is_sensitive']));
        $this->sot['is_sensitive'] = $v;
        $this->assertEquals($v, $this->sot['is_sensitive']);
        $this->assertTrue(isset($this->sot['is_sensitive']));
        $this->sot['is_sensitive'] = null;
        $this->assertFalse(isset($this->sot['is_sensitive']));
    }

    /**
     * Test attribute "hint_text"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getHintText
     * @legacy-covers ::setHintText
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyHintText(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['hint_text'],
            $this->allowedValues['hint_text'] ?? null
        );
        $this->sot->setHintText($v);
        $this->assertEquals($v, $this->sot->getHintText());
        $this->sot->setHintText(null);
        $this->assertNull($this->sot->getHintText());
        $this->sot->setHintText($v);

        $this->assertEquals($v, $this->sot['hint_text']);
        $v = $this->getFakeValue(
            $this->types['hint_text'],
            $this->allowedValues['hint_text'] ?? null
        );
        $this->sot['hint_text'] = $v;
        $this->assertTrue(isset($this->sot['hint_text']));
        $this->assertEquals($v, $this->sot['hint_text']);
        $this->assertEquals($v, $this->sot->getHintText());
        unset($this->sot['hint_text']);
        $this->assertFalse(isset($this->sot['hint_text']));
        $this->sot['hint_text'] = $v;
        $this->assertEquals($v, $this->sot['hint_text']);
        $this->assertTrue(isset($this->sot['hint_text']));
        $this->sot['hint_text'] = null;
        $this->assertFalse(isset($this->sot['hint_text']));
    }

    /**
     * Test attribute "initially_checked"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getInitiallyChecked
     * @legacy-covers ::setInitiallyChecked
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyInitiallyChecked(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['initially_checked'],
            $this->allowedValues['initially_checked'] ?? null
        );
        $this->sot->setInitiallyChecked($v);
        $this->assertEquals($v, $this->sot->getInitiallyChecked());
        $this->sot->setInitiallyChecked(null);
        $this->assertNull($this->sot->getInitiallyChecked());
        $this->sot->setInitiallyChecked($v);

        $this->assertEquals($v, $this->sot['initially_checked']);
        $v = $this->getFakeValue(
            $this->types['initially_checked'],
            $this->allowedValues['initially_checked'] ?? null
        );
        $this->sot['initially_checked'] = $v;
        $this->assertTrue(isset($this->sot['initially_checked']));
        $this->assertEquals($v, $this->sot['initially_checked']);
        $this->assertEquals($v, $this->sot->getInitiallyChecked());
        unset($this->sot['initially_checked']);
        $this->assertFalse(isset($this->sot['initially_checked']));
        $this->sot['initially_checked'] = $v;
        $this->assertEquals($v, $this->sot['initially_checked']);
        $this->assertTrue(isset($this->sot['initially_checked']));
        $this->sot['initially_checked'] = null;
        $this->assertFalse(isset($this->sot['initially_checked']));
    }

    /**
     * Test attribute "instructions"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getInstructions
     * @legacy-covers ::setInstructions
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyInstructions(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['instructions'],
            $this->allowedValues['instructions'] ?? null
        );
        $this->sot->setInstructions($v);
        $this->assertEquals($v, $this->sot->getInstructions());
        $this->sot->setInstructions(null);
        $this->assertNull($this->sot->getInstructions());
        $this->sot->setInstructions($v);

        $this->assertEquals($v, $this->sot['instructions']);
        $v = $this->getFakeValue(
            $this->types['instructions'],
            $this->allowedValues['instructions'] ?? null
        );
        $this->sot['instructions'] = $v;
        $this->assertTrue(isset($this->sot['instructions']));
        $this->assertEquals($v, $this->sot['instructions']);
        $this->assertEquals($v, $this->sot->getInstructions());
        unset($this->sot['instructions']);
        $this->assertFalse(isset($this->sot['instructions']));
        $this->sot['instructions'] = $v;
        $this->assertEquals($v, $this->sot['instructions']);
        $this->assertTrue(isset($this->sot['instructions']));
        $this->sot['instructions'] = null;
        $this->assertFalse(isset($this->sot['instructions']));
    }

    /**
     * Test attribute "label"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getLabel
     * @legacy-covers ::setLabel
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyLabel(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['label'],
            $this->allowedValues['label'] ?? null
        );
        $this->sot->setLabel($v);
        $this->assertEquals($v, $this->sot->getLabel());
        $this->sot->setLabel(null);
        $this->assertNull($this->sot->getLabel());
        $this->sot->setLabel($v);

        $this->assertEquals($v, $this->sot['label']);
        $v = $this->getFakeValue(
            $this->types['label'],
            $this->allowedValues['label'] ?? null
        );
        $this->sot['label'] = $v;
        $this->assertTrue(isset($this->sot['label']));
        $this->assertEquals($v, $this->sot['label']);
        $this->assertEquals($v, $this->sot->getLabel());
        unset($this->sot['label']);
        $this->assertFalse(isset($this->sot['label']));
        $this->sot['label'] = $v;
        $this->assertEquals($v, $this->sot['label']);
        $this->assertTrue(isset($this->sot['label']));
        $this->sot['label'] = null;
        $this->assertFalse(isset($this->sot['label']));
    }

    /**
     * Test attribute "label_to_right"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getLabelToRight
     * @legacy-covers ::setLabelToRight
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyLabelToRight(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['label_to_right'],
            $this->allowedValues['label_to_right'] ?? null
        );
        $this->sot->setLabelToRight($v);
        $this->assertEquals($v, $this->sot->getLabelToRight());
        $this->sot->setLabelToRight(null);
        $this->assertNull($this->sot->getLabelToRight());
        $this->sot->setLabelToRight($v);

        $this->assertEquals($v, $this->sot['label_to_right']);
        $v = $this->getFakeValue(
            $this->types['label_to_right'],
            $this->allowedValues['label_to_right'] ?? null
        );
        $this->sot['label_to_right'] = $v;
        $this->assertTrue(isset($this->sot['label_to_right']));
        $this->assertEquals($v, $this->sot['label_to_right']);
        $this->assertEquals($v, $this->sot->getLabelToRight());
        unset($this->sot['label_to_right']);
        $this->assertFalse(isset($this->sot['label_to_right']));
        $this->sot['label_to_right'] = $v;
        $this->assertEquals($v, $this->sot['label_to_right']);
        $this->assertTrue(isset($this->sot['label_to_right']));
        $this->sot['label_to_right'] = null;
        $this->assertFalse(isset($this->sot['label_to_right']));
    }

    /**
     * Test attribute "label_width"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getLabelWidth
     * @legacy-covers ::setLabelWidth
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyLabelWidth(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['label_width'],
            $this->allowedValues['label_width'] ?? null
        );
        $this->sot->setLabelWidth($v);
        $this->assertEquals($v, $this->sot->getLabelWidth());
        $this->sot->setLabelWidth(null);
        $this->assertNull($this->sot->getLabelWidth());
        $this->sot->setLabelWidth($v);

        $this->assertEquals($v, $this->sot['label_width']);
        $v = $this->getFakeValue(
            $this->types['label_width'],
            $this->allowedValues['label_width'] ?? null
        );
        $this->sot['label_width'] = $v;
        $this->assertTrue(isset($this->sot['label_width']));
        $this->assertEquals($v, $this->sot['label_width']);
        $this->assertEquals($v, $this->sot->getLabelWidth());
        unset($this->sot['label_width']);
        $this->assertFalse(isset($this->sot['label_width']));
        $this->sot['label_width'] = $v;
        $this->assertEquals($v, $this->sot['label_width']);
        $this->assertTrue(isset($this->sot['label_width']));
        $this->sot['label_width'] = null;
        $this->assertFalse(isset($this->sot['label_width']));
    }

    /**
     * Test attribute "mask_input"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getMaskInput
     * @legacy-covers ::setMaskInput
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyMaskInput(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['mask_input'],
            $this->allowedValues['mask_input'] ?? null
        );
        $this->sot->setMaskInput($v);
        $this->assertEquals($v, $this->sot->getMaskInput());
        $this->sot->setMaskInput(null);
        $this->assertNull($this->sot->getMaskInput());
        $this->sot->setMaskInput($v);

        $this->assertEquals($v, $this->sot['mask_input']);
        $v = $this->getFakeValue(
            $this->types['mask_input'],
            $this->allowedValues['mask_input'] ?? null
        );
        $this->sot['mask_input'] = $v;
        $this->assertTrue(isset($this->sot['mask_input']));
        $this->assertEquals($v, $this->sot['mask_input']);
        $this->assertEquals($v, $this->sot->getMaskInput());
        unset($this->sot['mask_input']);
        $this->assertFalse(isset($this->sot['mask_input']));
        $this->sot['mask_input'] = $v;
        $this->assertEquals($v, $this->sot['mask_input']);
        $this->assertTrue(isset($this->sot['mask_input']));
        $this->sot['mask_input'] = null;
        $this->assertFalse(isset($this->sot['mask_input']));
    }

    /**
     * Test attribute "max_length"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getMaxLength
     * @legacy-covers ::setMaxLength
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyMaxLength(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['max_length'],
            $this->allowedValues['max_length'] ?? null
        );
        $this->sot->setMaxLength($v);
        $this->assertEquals($v, $this->sot->getMaxLength());
        $this->sot->setMaxLength(null);
        $this->assertNull($this->sot->getMaxLength());
        $this->sot->setMaxLength($v);

        $this->assertEquals($v, $this->sot['max_length']);
        $v = $this->getFakeValue(
            $this->types['max_length'],
            $this->allowedValues['max_length'] ?? null
        );
        $this->sot['max_length'] = $v;
        $this->assertTrue(isset($this->sot['max_length']));
        $this->assertEquals($v, $this->sot['max_length']);
        $this->assertEquals($v, $this->sot->getMaxLength());
        unset($this->sot['max_length']);
        $this->assertFalse(isset($this->sot['max_length']));
        $this->sot['max_length'] = $v;
        $this->assertEquals($v, $this->sot['max_length']);
        $this->assertTrue(isset($this->sot['max_length']));
        $this->sot['max_length'] = null;
        $this->assertFalse(isset($this->sot['max_length']));
    }

    /**
     * Test attribute "max_value"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getMaxValue
     * @legacy-covers ::setMaxValue
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyMaxValue(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['max_value'],
            $this->allowedValues['max_value'] ?? null
        );
        $this->sot->setMaxValue($v);
        $this->assertEquals($v, $this->sot->getMaxValue());
        $this->sot->setMaxValue(null);
        $this->assertNull($this->sot->getMaxValue());
        $this->sot->setMaxValue($v);

        $this->assertEquals($v, $this->sot['max_value']);
        $v = $this->getFakeValue(
            $this->types['max_value'],
            $this->allowedValues['max_value'] ?? null
        );
        $this->sot['max_value'] = $v;
        $this->assertTrue(isset($this->sot['max_value']));
        $this->assertEquals($v, $this->sot['max_value']);
        $this->assertEquals($v, $this->sot->getMaxValue());
        unset($this->sot['max_value']);
        $this->assertFalse(isset($this->sot['max_value']));
        $this->sot['max_value'] = $v;
        $this->assertEquals($v, $this->sot['max_value']);
        $this->assertTrue(isset($this->sot['max_value']));
        $this->sot['max_value'] = null;
        $this->assertFalse(isset($this->sot['max_value']));
    }

    /**
     * Test attribute "min_value"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getMinValue
     * @legacy-covers ::setMinValue
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyMinValue(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['min_value'],
            $this->allowedValues['min_value'] ?? null
        );
        $this->sot->setMinValue($v);
        $this->assertEquals($v, $this->sot->getMinValue());
        $this->sot->setMinValue(null);
        $this->assertNull($this->sot->getMinValue());
        $this->sot->setMinValue($v);

        $this->assertEquals($v, $this->sot['min_value']);
        $v = $this->getFakeValue(
            $this->types['min_value'],
            $this->allowedValues['min_value'] ?? null
        );
        $this->sot['min_value'] = $v;
        $this->assertTrue(isset($this->sot['min_value']));
        $this->assertEquals($v, $this->sot['min_value']);
        $this->assertEquals($v, $this->sot->getMinValue());
        unset($this->sot['min_value']);
        $this->assertFalse(isset($this->sot['min_value']));
        $this->sot['min_value'] = $v;
        $this->assertEquals($v, $this->sot['min_value']);
        $this->assertTrue(isset($this->sot['min_value']));
        $this->sot['min_value'] = null;
        $this->assertFalse(isset($this->sot['min_value']));
    }

    /**
     * Test attribute "multi_select"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getMultiSelect
     * @legacy-covers ::setMultiSelect
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyMultiSelect(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['multi_select'],
            $this->allowedValues['multi_select'] ?? null
        );
        $this->sot->setMultiSelect($v);
        $this->assertEquals($v, $this->sot->getMultiSelect());
        $this->sot->setMultiSelect(null);
        $this->assertNull($this->sot->getMultiSelect());
        $this->sot->setMultiSelect($v);

        $this->assertEquals($v, $this->sot['multi_select']);
        $v = $this->getFakeValue(
            $this->types['multi_select'],
            $this->allowedValues['multi_select'] ?? null
        );
        $this->sot['multi_select'] = $v;
        $this->assertTrue(isset($this->sot['multi_select']));
        $this->assertEquals($v, $this->sot['multi_select']);
        $this->assertEquals($v, $this->sot->getMultiSelect());
        unset($this->sot['multi_select']);
        $this->assertFalse(isset($this->sot['multi_select']));
        $this->sot['multi_select'] = $v;
        $this->assertEquals($v, $this->sot['multi_select']);
        $this->assertTrue(isset($this->sot['multi_select']));
        $this->sot['multi_select'] = null;
        $this->assertFalse(isset($this->sot['multi_select']));
    }

    /**
     * Test attribute "required"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getRequired
     * @legacy-covers ::setRequired
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyRequired(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['required'],
            $this->allowedValues['required'] ?? null
        );
        $this->sot->setRequired($v);
        $this->assertEquals($v, $this->sot->getRequired());
        $this->sot->setRequired(null);
        $this->assertNull($this->sot->getRequired());
        $this->sot->setRequired($v);

        $this->assertEquals($v, $this->sot['required']);
        $v = $this->getFakeValue(
            $this->types['required'],
            $this->allowedValues['required'] ?? null
        );
        $this->sot['required'] = $v;
        $this->assertTrue(isset($this->sot['required']));
        $this->assertEquals($v, $this->sot['required']);
        $this->assertEquals($v, $this->sot->getRequired());
        unset($this->sot['required']);
        $this->assertFalse(isset($this->sot['required']));
        $this->sot['required'] = $v;
        $this->assertEquals($v, $this->sot['required']);
        $this->assertTrue(isset($this->sot['required']));
        $this->sot['required'] = null;
        $this->assertFalse(isset($this->sot['required']));
    }

    /**
     * Test attribute "validation_message"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getValidationMessage
     * @legacy-covers ::setValidationMessage
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyValidationMessage(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['validation_message'],
            $this->allowedValues['validation_message'] ?? null
        );
        $this->sot->setValidationMessage($v);
        $this->assertEquals($v, $this->sot->getValidationMessage());
        $this->sot->setValidationMessage(null);
        $this->assertNull($this->sot->getValidationMessage());
        $this->sot->setValidationMessage($v);

        $this->assertEquals($v, $this->sot['validation_message']);
        $v = $this->getFakeValue(
            $this->types['validation_message'],
            $this->allowedValues['validation_message'] ?? null
        );
        $this->sot['validation_message'] = $v;
        $this->assertTrue(isset($this->sot['validation_message']));
        $this->assertEquals($v, $this->sot['validation_message']);
        $this->assertEquals($v, $this->sot->getValidationMessage());
        unset($this->sot['validation_message']);
        $this->assertFalse(isset($this->sot['validation_message']));
        $this->sot['validation_message'] = $v;
        $this->assertEquals($v, $this->sot['validation_message']);
        $this->assertTrue(isset($this->sot['validation_message']));
        $this->sot['validation_message'] = null;
        $this->assertFalse(isset($this->sot['validation_message']));
    }

    /**
     * Test attribute "values"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getValues
     * @legacy-covers ::setValues
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyValues(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['values'],
            $this->allowedValues['values'] ?? null
        );
        $this->sot->setValues($v);
        $this->assertEquals($v, $this->sot->getValues());
        $this->sot->setValues(null);
        $this->assertNull($this->sot->getValues());
        $this->sot->setValues($v);

        $this->assertEquals($v, $this->sot['values']);
        $v = $this->getFakeValue(
            $this->types['values'],
            $this->allowedValues['values'] ?? null
        );
        $this->sot['values'] = $v;
        $this->assertTrue(isset($this->sot['values']));
        $this->assertEquals($v, $this->sot['values']);
        $this->assertEquals($v, $this->sot->getValues());
        unset($this->sot['values']);
        $this->assertFalse(isset($this->sot['values']));
        $this->sot['values'] = $v;
        $this->assertEquals($v, $this->sot['values']);
        $this->assertTrue(isset($this->sot['values']));
        $this->sot['values'] = null;
        $this->assertFalse(isset($this->sot['values']));
    }

    /**
     * Test attribute "visible_lines"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getVisibleLines
     * @legacy-covers ::setVisibleLines
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyVisibleLines(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['visible_lines'],
            $this->allowedValues['visible_lines'] ?? null
        );
        $this->sot->setVisibleLines($v);
        $this->assertEquals($v, $this->sot->getVisibleLines());
        $this->sot->setVisibleLines(null);
        $this->assertNull($this->sot->getVisibleLines());
        $this->sot->setVisibleLines($v);

        $this->assertEquals($v, $this->sot['visible_lines']);
        $v = $this->getFakeValue(
            $this->types['visible_lines'],
            $this->allowedValues['visible_lines'] ?? null
        );
        $this->sot['visible_lines'] = $v;
        $this->assertTrue(isset($this->sot['visible_lines']));
        $this->assertEquals($v, $this->sot['visible_lines']);
        $this->assertEquals($v, $this->sot->getVisibleLines());
        unset($this->sot['visible_lines']);
        $this->assertFalse(isset($this->sot['visible_lines']));
        $this->sot['visible_lines'] = $v;
        $this->assertEquals($v, $this->sot['visible_lines']);
        $this->assertTrue(isset($this->sot['visible_lines']));
        $this->sot['visible_lines'] = null;
        $this->assertFalse(isset($this->sot['visible_lines']));
    }

    /**
     * Test invalid use of offsetSet.
     *
     * @legacy-covers ::offsetSet
     */
    public function testInvalidOffsetException(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->sot[] = 'foobar';
    }
}
