<?php

/**
 * EmailCCFieldsTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Test\Model;

use Faker\Factory as FakerFactory;
use NecLimDul\MarketoRest\Asset\Model\ModelInterface;
use NecLimDul\MarketoRest\Asset\Model\EmailCCFields;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * EmailCCFieldsTest
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.18.0
 */
#[CoversClass(EmailCCFields::class)]
class EmailCCFieldsTest extends TestCase
{
    use FakeValuesTrait;

    private EmailCCFields $sot;

    /**
     * @var string[]
     */
    private array $types = [
        'attribute_id' => 'string',
        'object_name' => 'string',
        'display_name' => 'string',
        'api_name' => 'string',
    ];


    /**
     * @var scalar[][]
     */
    private array $allowedValues = [
    ];

    public function setUp(): void
    {
        parent::setUp();
        $this->setFaker(FakerFactory::create());
        $this->sot = $this->getFakeValue(EmailCCFields::class, null);
    }

    /**
     * Test "EmailCCFields"
     *
     * @legacy-covers ::__construct
     */
    public function testEmailCCFields(): void
    {
        $this->assertInstanceOf(EmailCCFields::class, $this->sot);
    }

    /**
     * @legacy-covers ::openAPITypes
     */
    public function testOpenApiTypes(): void
    {
        $this->assertEquals($this->types, EmailCCFields::openAPITypes());
    }

    /**
     * @legacy-covers ::openAPIRequired
     */
    public function testOpenAPIRequired(): void
    {
        $required = $this->sot->openAPIRequired();
        $this->assertEquals('attribute_id', $required['attribute_id']);
        $this->assertEquals('object_name', $required['object_name']);
        $this->assertEquals('display_name', $required['display_name']);
        $this->assertEquals('api_name', $required['api_name']);
    }

    /**
     * @legacy-covers ::openAPIFormats
     */
    public function testOpenAPIFormats(): void
    {
        $formats = $this->sot->openAPIFormats();
        $this->assertNotContains('attribute_id', $formats);
        $this->assertNotContains('object_name', $formats);
        $this->assertNotContains('display_name', $formats);
        $this->assertNotContains('api_name', $formats);
    }

    /**
     * @legacy-covers ::attributeMap
     */
    public function testAttributeMap(): void
    {
        $formats = $this->sot->attributeMap();
        $this->assertEquals('attributeId', $formats['attribute_id']);
        $this->assertEquals('objectName', $formats['object_name']);
        $this->assertEquals('displayName', $formats['display_name']);
        $this->assertEquals('apiName', $formats['api_name']);
    }

    /**
     * @legacy-covers ::getters
     * @legacy-covers ::setters
     */
    public function testGettersSetters(): void
    {
        $getters = $this->sot->getters();
        $setters = $this->sot->setters();
        foreach (array_keys($this->types) as $field) {
            $this->assertTrue(isset($setters[$field]));
            $this->assertTrue(isset($getters[$field]));
        }
    }

    /**
     * @legacy-covers ::getModelName
     */
    public function testGetModelName(): void
    {
        $this->assertEquals('EmailCCFields', $this->sot->getModelName());
    }

    /**
     * @legacy-covers ::setAdditionalProperties
     * @legacy-covers ::setAdditionalProperty
     * @legacy-covers ::getAdditionalProperties
     */
    public function testAdditionalProperties(): void
    {
        do {
            $property = $this->faker->word();
        } while (isset($this->sot::attributeMap()[$property]));
        $value = 'foobar';
        $this->sot[$property] = $value;
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperty($property, $value);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperties([
            $property => $value,
        ]);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        $this->assertEquals(
            $value,
            $this->sot->jsonSerialize()->$property
        );
    }

    /**
     * @legacy-covers ::setAdditionalProperty
     */
    public function testAdditionalPropertyExistingProperty(): void
    {
        $this->expectException(\AssertionError::class);
        $this->sot->setAdditionalProperty(key($this->sot::attributeMap()), 'foobar');
    }

    /**
     * @legacy-covers ::jsonSerialize
     * @legacy-covers ::__toString
     */
    public function testJson(): void
    {
        // Some minimal tests that json generates well.
        $json = json_encode($this->sot);
        $this->assertIsString($json, 'Json encoded');
        $json = json_decode($json);
        $string = json_decode((string) $this->sot);
        $this->assertEquals(
            $json,
            $string
        );
        $this->assertInstanceOf(\stdClass::class, $json);
        $this->assertInstanceOf(\stdClass::class, $string);
    }

    /**
     * Test attribute "attribute_id"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getAttributeId
     * @legacy-covers ::setAttributeId
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyAttributeId(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['attribute_id'],
            $this->allowedValues['attribute_id'] ?? null
        );
        $this->sot->setAttributeId($v);
        $this->assertEquals($v, $this->sot->getAttributeId());

        $this->assertEquals($v, $this->sot['attribute_id']);
        $v = $this->getFakeValue(
            $this->types['attribute_id'],
            $this->allowedValues['attribute_id'] ?? null
        );
        $this->sot['attribute_id'] = $v;
        $this->assertTrue(isset($this->sot['attribute_id']));
        $this->assertEquals($v, $this->sot['attribute_id']);
        $this->assertEquals($v, $this->sot->getAttributeId());
        unset($this->sot['attribute_id']);
        $this->assertFalse(isset($this->sot['attribute_id']));
        $this->sot['attribute_id'] = $v;
        $this->assertEquals($v, $this->sot['attribute_id']);
        $this->assertTrue(isset($this->sot['attribute_id']));
        $this->sot['attribute_id'] = null;
        $this->assertFalse(isset($this->sot['attribute_id']));
    }

    /**
     * Test attribute "object_name"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getObjectName
     * @legacy-covers ::setObjectName
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyObjectName(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['object_name'],
            $this->allowedValues['object_name'] ?? null
        );
        $this->sot->setObjectName($v);
        $this->assertEquals($v, $this->sot->getObjectName());

        $this->assertEquals($v, $this->sot['object_name']);
        $v = $this->getFakeValue(
            $this->types['object_name'],
            $this->allowedValues['object_name'] ?? null
        );
        $this->sot['object_name'] = $v;
        $this->assertTrue(isset($this->sot['object_name']));
        $this->assertEquals($v, $this->sot['object_name']);
        $this->assertEquals($v, $this->sot->getObjectName());
        unset($this->sot['object_name']);
        $this->assertFalse(isset($this->sot['object_name']));
        $this->sot['object_name'] = $v;
        $this->assertEquals($v, $this->sot['object_name']);
        $this->assertTrue(isset($this->sot['object_name']));
        $this->sot['object_name'] = null;
        $this->assertFalse(isset($this->sot['object_name']));
    }

    /**
     * Test attribute "display_name"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getDisplayName
     * @legacy-covers ::setDisplayName
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyDisplayName(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['display_name'],
            $this->allowedValues['display_name'] ?? null
        );
        $this->sot->setDisplayName($v);
        $this->assertEquals($v, $this->sot->getDisplayName());

        $this->assertEquals($v, $this->sot['display_name']);
        $v = $this->getFakeValue(
            $this->types['display_name'],
            $this->allowedValues['display_name'] ?? null
        );
        $this->sot['display_name'] = $v;
        $this->assertTrue(isset($this->sot['display_name']));
        $this->assertEquals($v, $this->sot['display_name']);
        $this->assertEquals($v, $this->sot->getDisplayName());
        unset($this->sot['display_name']);
        $this->assertFalse(isset($this->sot['display_name']));
        $this->sot['display_name'] = $v;
        $this->assertEquals($v, $this->sot['display_name']);
        $this->assertTrue(isset($this->sot['display_name']));
        $this->sot['display_name'] = null;
        $this->assertFalse(isset($this->sot['display_name']));
    }

    /**
     * Test attribute "api_name"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getApiName
     * @legacy-covers ::setApiName
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyApiName(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['api_name'],
            $this->allowedValues['api_name'] ?? null
        );
        $this->sot->setApiName($v);
        $this->assertEquals($v, $this->sot->getApiName());

        $this->assertEquals($v, $this->sot['api_name']);
        $v = $this->getFakeValue(
            $this->types['api_name'],
            $this->allowedValues['api_name'] ?? null
        );
        $this->sot['api_name'] = $v;
        $this->assertTrue(isset($this->sot['api_name']));
        $this->assertEquals($v, $this->sot['api_name']);
        $this->assertEquals($v, $this->sot->getApiName());
        unset($this->sot['api_name']);
        $this->assertFalse(isset($this->sot['api_name']));
        $this->sot['api_name'] = $v;
        $this->assertEquals($v, $this->sot['api_name']);
        $this->assertTrue(isset($this->sot['api_name']));
        $this->sot['api_name'] = null;
        $this->assertFalse(isset($this->sot['api_name']));
    }

    /**
     * Test invalid use of offsetSet.
     *
     * @legacy-covers ::offsetSet
     */
    public function testInvalidOffsetException(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->sot[] = 'foobar';
    }
}
