<?php

/**
 * FolderTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Test\Model;

use Faker\Factory as FakerFactory;
use NecLimDul\MarketoRest\Asset\Model\ModelInterface;
use NecLimDul\MarketoRest\Asset\Model\Folder;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * FolderTest
 *
 * JSON representation of a folder
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.18.0
 */
#[CoversClass(Folder::class)]
class FolderTest extends TestCase
{
    use FakeValuesTrait;

    private Folder $sot;

    /**
     * @var string[]
     */
    private array $types = [
        'id' => 'int',
        'type' => 'string',
    ];


    /**
     * @var scalar[][]
     */
    private array $allowedValues = [
        'type' => [
            'FOLDER' => 'Folder',
            'PROGRAM' => 'Program',
        ],
    ];

    public function setUp(): void
    {
        parent::setUp();
        $this->setFaker(FakerFactory::create());
        $this->sot = $this->getFakeValue(Folder::class, null);
    }

    /**
     * Test "Folder"
     *
     * @legacy-covers ::__construct
     */
    public function testFolder(): void
    {
        $this->assertInstanceOf(Folder::class, $this->sot);
    }

    /**
     * @legacy-covers ::openAPITypes
     */
    public function testOpenApiTypes(): void
    {
        $this->assertEquals($this->types, Folder::openAPITypes());
    }

    /**
     * @legacy-covers ::openAPIRequired
     */
    public function testOpenAPIRequired(): void
    {
        $required = $this->sot->openAPIRequired();
        $this->assertEquals('id', $required['id']);
        $this->assertEquals('type', $required['type']);
    }

    /**
     * @legacy-covers ::openAPIFormats
     */
    public function testOpenAPIFormats(): void
    {
        $formats = $this->sot->openAPIFormats();
        $this->assertEquals('int32', $formats['id']);
        $this->assertNotContains('type', $formats);
    }

    /**
     * @legacy-covers ::attributeMap
     */
    public function testAttributeMap(): void
    {
        $formats = $this->sot->attributeMap();
        $this->assertEquals('id', $formats['id']);
        $this->assertEquals('type', $formats['type']);
    }

    /**
     * @legacy-covers ::getters
     * @legacy-covers ::setters
     */
    public function testGettersSetters(): void
    {
        $getters = $this->sot->getters();
        $setters = $this->sot->setters();
        foreach (array_keys($this->types) as $field) {
            $this->assertTrue(isset($setters[$field]));
            $this->assertTrue(isset($getters[$field]));
        }
    }

    /**
     * @legacy-covers ::getModelName
     */
    public function testGetModelName(): void
    {
        $this->assertEquals('Folder', $this->sot->getModelName());
    }

    /**
     * @legacy-covers ::setAdditionalProperties
     * @legacy-covers ::setAdditionalProperty
     * @legacy-covers ::getAdditionalProperties
     */
    public function testAdditionalProperties(): void
    {
        do {
            $property = $this->faker->word();
        } while (isset($this->sot::attributeMap()[$property]));
        $value = 'foobar';
        $this->sot[$property] = $value;
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperty($property, $value);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperties([
            $property => $value,
        ]);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        $this->assertEquals(
            $value,
            $this->sot->jsonSerialize()->$property
        );
    }

    /**
     * @legacy-covers ::setAdditionalProperty
     */
    public function testAdditionalPropertyExistingProperty(): void
    {
        $this->expectException(\AssertionError::class);
        $this->sot->setAdditionalProperty(key($this->sot::attributeMap()), 'foobar');
    }

    /**
     * @legacy-covers ::jsonSerialize
     * @legacy-covers ::__toString
     */
    public function testJson(): void
    {
        // Some minimal tests that json generates well.
        $json = json_encode($this->sot);
        $this->assertIsString($json, 'Json encoded');
        $json = json_decode($json);
        $string = json_decode((string) $this->sot);
        $this->assertEquals(
            $json,
            $string
        );
        $this->assertInstanceOf(\stdClass::class, $json);
        $this->assertInstanceOf(\stdClass::class, $string);
    }

    /**
     * Test attribute "id"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getId
     * @legacy-covers ::setId
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyId(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['id'],
            $this->allowedValues['id'] ?? null
        );
        $this->sot->setId($v);
        $this->assertEquals($v, $this->sot->getId());

        $this->assertEquals($v, $this->sot['id']);
        $v = $this->getFakeValue(
            $this->types['id'],
            $this->allowedValues['id'] ?? null
        );
        $this->sot['id'] = $v;
        $this->assertTrue(isset($this->sot['id']));
        $this->assertEquals($v, $this->sot['id']);
        $this->assertEquals($v, $this->sot->getId());
        unset($this->sot['id']);
        $this->assertFalse(isset($this->sot['id']));
        $this->sot['id'] = $v;
        $this->assertEquals($v, $this->sot['id']);
        $this->assertTrue(isset($this->sot['id']));
        $this->sot['id'] = null;
        $this->assertFalse(isset($this->sot['id']));
    }

    /**
     * Test attribute "type"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getType
     * @legacy-covers ::setType
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyType(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['type'],
            $this->allowedValues['type'] ?? null
        );
        $this->sot->setType($v);
        $this->assertEquals($v, $this->sot->getType());

        $this->assertEquals($v, $this->sot['type']);
        $v = $this->getFakeValue(
            $this->types['type'],
            $this->allowedValues['type'] ?? null
        );
        $this->sot['type'] = $v;
        $this->assertTrue(isset($this->sot['type']));
        $this->assertEquals($v, $this->sot['type']);
        $this->assertEquals($v, $this->sot->getType());
        unset($this->sot['type']);
        $this->assertFalse(isset($this->sot['type']));
        $this->sot['type'] = $v;
        $this->assertEquals($v, $this->sot['type']);
        $this->assertTrue(isset($this->sot['type']));
        $this->sot['type'] = null;
        $this->assertFalse(isset($this->sot['type']));
    }

    /**
     * Trivial allowed values test.
     *
     * @legacy-covers ::getTypeAllowableValues()
     */
    public function testTypeAllowableValues(): void
    {
        // Trivial allowed values test.
        $this->assertEquals(array_values($this->allowedValues['type']), $this->sot->getTypeAllowableValues());
        foreach ($this->allowedValues['type'] as $v) {
            $this->sot->setType($v);
            $this->assertEquals($v, $this->sot->getType());
        }
    }

    /**
     * @legacy-covers ::setType
     */
    public function testTypeNotAllowableValues(): void
    {
        $this->markTestIncomplete();
        // Find a value that's not allowed.
        do {
            $v = $this->getFakeValue($this->types['type'], null);
        } while (!isset($v) || in_array($v, $this->allowedValues['type'], true));
        $this->expectException(\InvalidArgumentException::class);
        $this->sot->setType($v);
        throw new \Exception(var_export($v, true) . " should have triggered an error...");
    }

    /**
     * Test invalid use of offsetSet.
     *
     * @legacy-covers ::offsetSet
     */
    public function testInvalidOffsetException(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->sot[] = 'foobar';
    }
}
