<?php
/**
 * FormThankYouPageDTOTest
 *
 * PHP version 7
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Asset
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

// namespace NecLimDul\MarketoRest\Asset;
namespace NecLimDul\MarketoRest\Asset\Model;

use PHPUnit\Framework\TestCase;

/**
 * FormThankYouPageDTOTest Class Doc Comment
 *
 * @category    Class
 * @description FormThankYouPageDTO
 * @package     NecLimDul\MarketoRest\Asset
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormThankYouPageDTOTest extends TestCase
{

    /**
     * Test "FormThankYouPageDTO"
     */
    public function testFormThankYouPageDTO()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "default"
     */
    public function testPropertyDefault()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "followup_type"
     */
    public function testPropertyFollowupType()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "followup_value"
     */
    public function testPropertyFollowupValue()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "operator"
     */
    public function testPropertyOperator()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "subject_field"
     */
    public function testPropertySubjectField()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {
        $class = new FormThankYouPageDTO();
        $this->assertTrue(TRUE);
    }
}
