<?php

/**
 * UpdateFolderRequestTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Test\Model;

use Faker\Factory as FakerFactory;
use NecLimDul\MarketoRest\Asset\Model\ModelInterface;
use NecLimDul\MarketoRest\Asset\Model\UpdateFolderRequest;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * UpdateFolderRequestTest
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.21.0
 */
#[CoversClass(UpdateFolderRequest::class)]
class UpdateFolderRequestTest extends TestCase
{
    use FakeValuesTrait;

    private UpdateFolderRequest $sot;

    /**
     * @var string[]
     */
    private array $types = [
        'description' => 'string',
        'is_archive' => 'bool',
        'name' => 'string',
        'type' => 'string',
    ];

    /**
     * @var scalar[][]
     */
    private array $allowedValues = [
        'type' => [
            'FOLDER' => 'Folder',
            'PROGRAM' => 'Program',
        ],
    ];

    public function setUp(): void
    {
        parent::setUp();
        $this->setFaker(FakerFactory::create());
        $this->sot = $this->getFakeValue(UpdateFolderRequest::class, null);
    }

    /**
     * Test "UpdateFolderRequest"
     *
     * @legacy-covers ::__construct
     */
    public function testUpdateFolderRequest(): void
    {
        $this->assertInstanceOf(UpdateFolderRequest::class, $this->sot);
    }

    /**
     * @legacy-covers ::openAPITypes
     */
    public function testOpenApiTypes(): void
    {
        $this->assertEquals($this->types, UpdateFolderRequest::openAPITypes());
    }

    /**
     * @legacy-covers ::openAPIRequired
     */
    public function testOpenAPIRequired(): void
    {
        $required = $this->sot->openAPIRequired();
        $this->assertNotContains('description', $required);
        $this->assertNotContains('is_archive', $required);
        $this->assertNotContains('name', $required);
        $this->assertEquals('type', $required['type']);
    }

    /**
     * @legacy-covers ::openAPIFormats
     */
    public function testOpenAPIFormats(): void
    {
        $formats = $this->sot->openAPIFormats();
        $this->assertNotContains('description', $formats);
        $this->assertNotContains('is_archive', $formats);
        $this->assertNotContains('name', $formats);
        $this->assertNotContains('type', $formats);
    }

    /**
     * @legacy-covers ::attributeMap
     */
    public function testAttributeMap(): void
    {
        $attributes = $this->sot->attributeMap();
        $this->assertEquals('description', $attributes['description']);
        $this->assertEquals('isArchive', $attributes['is_archive']);
        $this->assertEquals('name', $attributes['name']);
        $this->assertEquals('type', $attributes['type']);
    }

    /**
     * @legacy-covers ::getters
     * @legacy-covers ::setters
     */
    public function testGettersSetters(): void
    {
        $getters = $this->sot->getters();
        $setters = $this->sot->setters();
        foreach (array_keys($this->types) as $field) {
            $this->assertTrue(isset($setters[$field]));
            $this->assertTrue(isset($getters[$field]));
        }
    }

    /**
     * @legacy-covers ::getModelName
     */
    public function testGetModelName(): void
    {
        $this->assertEquals('UpdateFolderRequest', $this->sot->getModelName());
    }

    /**
     * @legacy-covers ::setAdditionalProperties
     * @legacy-covers ::setAdditionalProperty
     * @legacy-covers ::getAdditionalProperties
     */
    public function testAdditionalProperties(): void
    {
        do {
            $property = $this->faker->word();
        } while (isset($this->sot::attributeMap()[$property]));
        $value = 'foobar';
        $this->sot[$property] = $value;
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperty($property, $value);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        unset($this->sot[$property]);
        $this->assertArrayNotHasKey($property, $this->sot);
        $this->sot->setAdditionalProperties([
            $property => $value,
        ]);
        $this->assertArrayHasKey($property, $this->sot);
        $this->assertEquals($value, $this->sot->getAdditionalProperties()[$property]);
        $this->assertEquals(
            $value,
            $this->sot->jsonSerialize()->$property
        );
    }

    /**
     * @legacy-covers ::setAdditionalProperty
     */
    public function testAdditionalPropertyExistingProperty(): void
    {
        $this->expectException(\AssertionError::class);
        $this->sot->setAdditionalProperty(key($this->sot::attributeMap()), 'foobar');
    }

    /**
     * @legacy-covers ::jsonSerialize
     * @legacy-covers ::__toString
     */
    public function testJson(): void
    {
        // Some minimal tests that json generates well.
        $json = json_encode($this->sot);
        $this->assertIsString($json, 'Json encoded');
        $json = json_decode($json);
        $string = json_decode((string) $this->sot);
        $this->assertEquals(
            $json,
            $string
        );
        $this->assertInstanceOf(\stdClass::class, $json);
        $this->assertInstanceOf(\stdClass::class, $string);
    }

    /**
     * Test attribute "description"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getDescription
     * @legacy-covers ::setDescription
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyDescription(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['description'],
            $this->allowedValues['description'] ?? null
        );
        $this->sot->setDescription($v);
        $this->assertEquals($v, $this->sot->getDescription());
        $this->sot->setDescription(null);
        $this->assertNull($this->sot->getDescription());
        $this->sot->setDescription($v);

        $this->assertEquals($v, $this->sot['description']);
        $v = $this->getFakeValue(
            $this->types['description'],
            $this->allowedValues['description'] ?? null
        );
        $this->sot['description'] = $v;
        $this->assertTrue(isset($this->sot['description']));
        $this->assertEquals($v, $this->sot['description']);
        $this->assertEquals($v, $this->sot->getDescription());
        unset($this->sot['description']);
        $this->assertFalse(isset($this->sot['description']));
        $this->sot['description'] = $v;
        $this->assertEquals($v, $this->sot['description']);
        $this->assertTrue(isset($this->sot['description']));
        $this->sot['description'] = null;
        $this->assertFalse(isset($this->sot['description']));
    }

    /**
     * Test attribute "is_archive"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getIsArchive
     * @legacy-covers ::setIsArchive
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyIsArchive(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['is_archive'],
            $this->allowedValues['is_archive'] ?? null
        );
        $this->sot->setIsArchive($v);
        $this->assertEquals($v, $this->sot->getIsArchive());
        $this->sot->setIsArchive(null);
        $this->assertNull($this->sot->getIsArchive());
        $this->sot->setIsArchive($v);

        $this->assertEquals($v, $this->sot['is_archive']);
        $v = $this->getFakeValue(
            $this->types['is_archive'],
            $this->allowedValues['is_archive'] ?? null
        );
        $this->sot['is_archive'] = $v;
        $this->assertTrue(isset($this->sot['is_archive']));
        $this->assertEquals($v, $this->sot['is_archive']);
        $this->assertEquals($v, $this->sot->getIsArchive());
        unset($this->sot['is_archive']);
        $this->assertFalse(isset($this->sot['is_archive']));
        $this->sot['is_archive'] = $v;
        $this->assertEquals($v, $this->sot['is_archive']);
        $this->assertTrue(isset($this->sot['is_archive']));
        $this->sot['is_archive'] = null;
        $this->assertFalse(isset($this->sot['is_archive']));
    }

    /**
     * Test attribute "name"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getName
     * @legacy-covers ::setName
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyName(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['name'],
            $this->allowedValues['name'] ?? null
        );
        $this->sot->setName($v);
        $this->assertEquals($v, $this->sot->getName());
        $this->sot->setName(null);
        $this->assertNull($this->sot->getName());
        $this->sot->setName($v);

        $this->assertEquals($v, $this->sot['name']);
        $v = $this->getFakeValue(
            $this->types['name'],
            $this->allowedValues['name'] ?? null
        );
        $this->sot['name'] = $v;
        $this->assertTrue(isset($this->sot['name']));
        $this->assertEquals($v, $this->sot['name']);
        $this->assertEquals($v, $this->sot->getName());
        unset($this->sot['name']);
        $this->assertFalse(isset($this->sot['name']));
        $this->sot['name'] = $v;
        $this->assertEquals($v, $this->sot['name']);
        $this->assertTrue(isset($this->sot['name']));
        $this->sot['name'] = null;
        $this->assertFalse(isset($this->sot['name']));
    }

    /**
     * Test attribute "type"
     *
     * @legacy-covers ::__construct
     * @legacy-covers ::getType
     * @legacy-covers ::setType
     * @legacy-covers ::offsetExists
     * @legacy-covers ::offsetGet
     * @legacy-covers ::offsetSet
     * @legacy-covers ::offsetUnset
     */
    public function testPropertyType(): void
    {
        // @todo can we assert anything useful about the default?
        $v = $this->getFakeValue(
            $this->types['type'],
            $this->allowedValues['type'] ?? null
        );
        $this->sot->setType($v);
        $this->assertEquals($v, $this->sot->getType());

        $this->assertEquals($v, $this->sot['type']);
        $v = $this->getFakeValue(
            $this->types['type'],
            $this->allowedValues['type'] ?? null
        );
        $this->sot['type'] = $v;
        $this->assertTrue(isset($this->sot['type']));
        $this->assertEquals($v, $this->sot['type']);
        $this->assertEquals($v, $this->sot->getType());
        unset($this->sot['type']);
        $this->assertFalse(isset($this->sot['type']));
        $this->sot['type'] = $v;
        $this->assertEquals($v, $this->sot['type']);
        $this->assertTrue(isset($this->sot['type']));
        $this->sot['type'] = null;
        $this->assertFalse(isset($this->sot['type']));
    }

    /**
     * Trivial allowed values test.
     *
     * @legacy-covers ::getTypeAllowableValues()
     */
    public function testTypeAllowableValues(): void
    {
        // Trivial allowed values test.
        $this->assertEquals(array_values($this->allowedValues['type']), $this->sot->getTypeAllowableValues());
        foreach ($this->allowedValues['type'] as $v) {
            $this->sot->setType($v);
            $this->assertEquals($v, $this->sot->getType());
        }
    }

    /**
     * @legacy-covers ::setType
     */
    public function testTypeNotAllowableValues(): void
    {
        $this->markTestIncomplete('Broken my property overloading and needs additional work');
        // Find a value that's not allowed.
        do {
            $v = $this->getFakeValue($this->types['type'], null);
        } while (!isset($v) || in_array($v, $this->allowedValues['type'], true));
        $this->expectException(\InvalidArgumentException::class);
        $this->sot->setType($v);
        throw new \Exception(var_export($v, true) . " should have triggered an error...");
    }

    /**
     * Test invalid use of offsetSet.
     *
     * @legacy-covers ::offsetSet
     */
    public function testInvalidOffsetException(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->sot[] = 'foobar';
    }
}
