runs:
  using: "composite"
  steps:
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v5
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - uses: php-actions/composer@v6
