<?php

/**
 * BulkExportLeadsApi class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NecLimDul\MarketoRest\Lead\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\Request;
use Neclimdul\OpenapiPhp\Helper\RequestHelperTrait;
use Psr\Http\Message\ResponseInterface;
use NecLimDul\MarketoRest\Lead\ApiException;
use NecLimDul\MarketoRest\Lead\Configuration;
use NecLimDul\MarketoRest\Lead\HeaderSelector;
use NecLimDul\MarketoRest\Lead\ObjectSerializer;

/**
 * BulkExportLeadsApi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.13.0
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BulkExportLeadsApi
{
    /**
     * @use RequestHelperTrait<ApiException,\NecLimDul\MarketoRest\Lead\Model\ModelInterface>
     */
    use RequestHelperTrait;

    protected Configuration $config;

    protected HeaderSelector $headerSelector;

    /**
     * @param (\GuzzleHttp\ClientInterface&\Psr\Http\Client\ClientInterface)|null $client
     * @param Configuration|null $config
     * @param HeaderSelector|null $selector
     * @param int $hostIndex
     *   (Optional) Host index to select the list of hosts if defined in the spec.
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        protected int $hostIndex = 0
    ) {
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->setSerializerForRequest(ObjectSerializer::getDefaultSerializer());
        $this->setConfigForRequest($this->config);
        $this->setClientForRequest($client ?: new Client());
        $this->setExceptionForRequest(ApiException::class);
    }

    /**
     * Set the host index.
     *
     * @param int $hostIndex
     *   Host index (required).
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index.
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * Get current configuration.
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Exception handler for cancelExportLeadsUsingPOST.
     *
     * @param \NecLimDul\MarketoRest\Lead\ApiException $e
     *   Unprocessed exception.
     *
     * @return \NecLimDul\MarketoRest\Lead\ApiException
     *   Processed exception.
     */
    protected function cancelExportLeadsUsingPOSTHandleException(ApiException $e): ApiException
    {
        switch ($e->getCode()) {
            case 200:
                $e->setResponseObject(
                    ObjectSerializer::deserialize(
                        $e->getResponseBody() ?? '',
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class,
                        $e->getResponseHeaders()
                    )
                );
                break;
        }
        return $e;
    }

    /**
     * Cancel Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse
     */
    public function cancelExportLeadsUsingPOST(
        string $export_id
    ): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse {
        [$response] = $this->cancelExportLeadsUsingPOSTWithHttpInfo($export_id);
        return $response;
    }

    /**
     * Cancel Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of the response, status code, and headers.
     * @psalm-suppress MoreSpecificReturnType
     * @psalm-suppress InvalidReturnType
     * @phpstan-return array{
     *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
     *     int,
     *     array<array<string>>
     * }
     */
    public function cancelExportLeadsUsingPOSTWithHttpInfo(
        string $export_id
    ): array {
        $request = $this->cancelExportLeadsUsingPOSTRequest($export_id);
        try {
            $response = $this->makeRequest($request);
        } catch (ApiException $e) {
            throw $this->cancelExportLeadsUsingPOSTHandleException($e);
        }
        /**
         * @psalm-suppress LessSpecificReturnStatement
         * @psalm-suppress InvalidReturnStatement
         */
        return match ($response->getStatusCode()) {
            200 => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
            default => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
        };
    }

    /**
     * Cancel Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     */
    public function cancelExportLeadsUsingPOSTAsync(
        string $export_id
    ): PromiseInterface {
        return $this->cancelExportLeadsUsingPOSTAsyncWithHttpInfo($export_id)
            ->then(
                /**
                 * @phpstan-param array{
                 *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
                 *     int,
                 *     array<array<string>>
                 * } $response
                 */
                fn(array $response): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse => $response[0]
            );
    }

    /**
     * Cancel Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cancelExportLeadsUsingPOSTAsyncWithHttpInfo(
        string $export_id
    ): PromiseInterface {
        return $this->makeAsyncRequest(
            $this->cancelExportLeadsUsingPOSTRequest($export_id),
            [$this, 'cancelExportLeadsUsingPOSTHandleException']
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface && $r->getStatusCode() == 200) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        );
    }

    /**
     * Create request for operation 'cancelExportLeadsUsingPOST'
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cancelExportLeadsUsingPOSTRequest(
        string $export_id
    ): Request {
        $resourcePath = '/bulk/v1/leads/export/{exportId}/cancel.json';
        $resourcePath = str_replace(
            '{' . 'exportId' . '}',
            ObjectSerializer::toPathValue($export_id),
            $resourcePath
        );
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($headers, $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        ));
        $operationHost = $this->config->getHost();

        // figure out header select logic.
        return $this->createRequest(
            'POST',
            $operationHost . $resourcePath,
            // Query.
            [
            ],
            // Headers.
            array_merge(
                [
                ],
                $headers
            ),
            // Form Params
            [
            ],
            ''
        );
    }

    /**
     * Exception handler for createExportLeadsUsingPOST.
     *
     * @param \NecLimDul\MarketoRest\Lead\ApiException $e
     *   Unprocessed exception.
     *
     * @return \NecLimDul\MarketoRest\Lead\ApiException
     *   Processed exception.
     */
    protected function createExportLeadsUsingPOSTHandleException(ApiException $e): ApiException
    {
        switch ($e->getCode()) {
            case 200:
                $e->setResponseObject(
                    ObjectSerializer::deserialize(
                        $e->getResponseBody() ?? '',
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class,
                        $e->getResponseHeaders()
                    )
                );
                break;
        }
        return $e;
    }

    /**
     * Create Export Lead Job
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest|null $export_lead_request
     *   exportLeadRequest&lt;br&gt;&lt;br&gt;ColumnHeaderNames: A JSON object containing key-value pairs of field and column header names.&lt;br&gt;&lt;br&gt;Example:&lt;br&gt;&lt;code&gt;\&quot;columnHeaderNames\&quot;:{&lt;br&gt;  \&quot;firstName\&quot;:\&quot;First Name\&quot;,&lt;br&gt;  \&quot;lastName\&quot;:\&quot;Last Name\&quot;,&lt;br&gt;  \&quot;email\&quot;:\&quot;Email Address\&quot;&lt;br&gt;}&lt;/code&gt;&lt;br&gt;
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse
     */
    public function createExportLeadsUsingPOST(
        ?\NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest $export_lead_request = null
    ): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse {
        [$response] = $this->createExportLeadsUsingPOSTWithHttpInfo($export_lead_request);
        return $response;
    }

    /**
     * Create Export Lead Job
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest|null $export_lead_request
     *   exportLeadRequest&lt;br&gt;&lt;br&gt;ColumnHeaderNames: A JSON object containing key-value pairs of field and column header names.&lt;br&gt;&lt;br&gt;Example:&lt;br&gt;&lt;code&gt;\&quot;columnHeaderNames\&quot;:{&lt;br&gt;  \&quot;firstName\&quot;:\&quot;First Name\&quot;,&lt;br&gt;  \&quot;lastName\&quot;:\&quot;Last Name\&quot;,&lt;br&gt;  \&quot;email\&quot;:\&quot;Email Address\&quot;&lt;br&gt;}&lt;/code&gt;&lt;br&gt;
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of the response, status code, and headers.
     * @psalm-suppress MoreSpecificReturnType
     * @psalm-suppress InvalidReturnType
     * @phpstan-return array{
     *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
     *     int,
     *     array<array<string>>
     * }
     */
    public function createExportLeadsUsingPOSTWithHttpInfo(
        ?\NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest $export_lead_request = null
    ): array {
        $request = $this->createExportLeadsUsingPOSTRequest($export_lead_request);
        try {
            $response = $this->makeRequest($request);
        } catch (ApiException $e) {
            throw $this->createExportLeadsUsingPOSTHandleException($e);
        }
        /**
         * @psalm-suppress LessSpecificReturnStatement
         * @psalm-suppress InvalidReturnStatement
         */
        return match ($response->getStatusCode()) {
            200 => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
            default => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
        };
    }

    /**
     * Create Export Lead Job
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest|null $export_lead_request
     *   exportLeadRequest&lt;br&gt;&lt;br&gt;ColumnHeaderNames: A JSON object containing key-value pairs of field and column header names.&lt;br&gt;&lt;br&gt;Example:&lt;br&gt;&lt;code&gt;\&quot;columnHeaderNames\&quot;:{&lt;br&gt;  \&quot;firstName\&quot;:\&quot;First Name\&quot;,&lt;br&gt;  \&quot;lastName\&quot;:\&quot;Last Name\&quot;,&lt;br&gt;  \&quot;email\&quot;:\&quot;Email Address\&quot;&lt;br&gt;}&lt;/code&gt;&lt;br&gt;
     *
     * @throws \InvalidArgumentException
     */
    public function createExportLeadsUsingPOSTAsync(
        ?\NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest $export_lead_request = null
    ): PromiseInterface {
        return $this->createExportLeadsUsingPOSTAsyncWithHttpInfo($export_lead_request)
            ->then(
                /**
                 * @phpstan-param array{
                 *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
                 *     int,
                 *     array<array<string>>
                 * } $response
                 */
                fn(array $response): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse => $response[0]
            );
    }

    /**
     * Create Export Lead Job
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest|null $export_lead_request
     *   exportLeadRequest&lt;br&gt;&lt;br&gt;ColumnHeaderNames: A JSON object containing key-value pairs of field and column header names.&lt;br&gt;&lt;br&gt;Example:&lt;br&gt;&lt;code&gt;\&quot;columnHeaderNames\&quot;:{&lt;br&gt;  \&quot;firstName\&quot;:\&quot;First Name\&quot;,&lt;br&gt;  \&quot;lastName\&quot;:\&quot;Last Name\&quot;,&lt;br&gt;  \&quot;email\&quot;:\&quot;Email Address\&quot;&lt;br&gt;}&lt;/code&gt;&lt;br&gt;
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createExportLeadsUsingPOSTAsyncWithHttpInfo(
        ?\NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest $export_lead_request = null
    ): PromiseInterface {
        return $this->makeAsyncRequest(
            $this->createExportLeadsUsingPOSTRequest($export_lead_request),
            [$this, 'createExportLeadsUsingPOSTHandleException']
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface && $r->getStatusCode() == 200) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        );
    }

    /**
     * Create request for operation 'createExportLeadsUsingPOST'
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest|null $export_lead_request
     *   exportLeadRequest&lt;br&gt;&lt;br&gt;ColumnHeaderNames: A JSON object containing key-value pairs of field and column header names.&lt;br&gt;&lt;br&gt;Example:&lt;br&gt;&lt;code&gt;\&quot;columnHeaderNames\&quot;:{&lt;br&gt;  \&quot;firstName\&quot;:\&quot;First Name\&quot;,&lt;br&gt;  \&quot;lastName\&quot;:\&quot;Last Name\&quot;,&lt;br&gt;  \&quot;email\&quot;:\&quot;Email Address\&quot;&lt;br&gt;}&lt;/code&gt;&lt;br&gt;
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createExportLeadsUsingPOSTRequest(
        ?\NecLimDul\MarketoRest\Lead\Model\ExportLeadRequest $export_lead_request = null
    ): Request {
        $resourcePath = '/bulk/v1/leads/export/create.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($headers, $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        ));
        $operationHost = $this->config->getHost();

        // figure out header select logic.
        return $this->createRequest(
            'POST',
            $operationHost . $resourcePath,
            // Query.
            [
            ],
            // Headers.
            array_merge(
                [
                ],
                $headers
            ),
            // Form Params
            [
            ],
            $export_lead_request
        );
    }

    /**
     * Exception handler for enqueueExportLeadsUsingPOST.
     *
     * @param \NecLimDul\MarketoRest\Lead\ApiException $e
     *   Unprocessed exception.
     *
     * @return \NecLimDul\MarketoRest\Lead\ApiException
     *   Processed exception.
     */
    protected function enqueueExportLeadsUsingPOSTHandleException(ApiException $e): ApiException
    {
        switch ($e->getCode()) {
            case 200:
                $e->setResponseObject(
                    ObjectSerializer::deserialize(
                        $e->getResponseBody() ?? '',
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class,
                        $e->getResponseHeaders()
                    )
                );
                break;
        }
        return $e;
    }

    /**
     * Enqueue Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse
     */
    public function enqueueExportLeadsUsingPOST(
        string $export_id
    ): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse {
        [$response] = $this->enqueueExportLeadsUsingPOSTWithHttpInfo($export_id);
        return $response;
    }

    /**
     * Enqueue Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of the response, status code, and headers.
     * @psalm-suppress MoreSpecificReturnType
     * @psalm-suppress InvalidReturnType
     * @phpstan-return array{
     *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
     *     int,
     *     array<array<string>>
     * }
     */
    public function enqueueExportLeadsUsingPOSTWithHttpInfo(
        string $export_id
    ): array {
        $request = $this->enqueueExportLeadsUsingPOSTRequest($export_id);
        try {
            $response = $this->makeRequest($request);
        } catch (ApiException $e) {
            throw $this->enqueueExportLeadsUsingPOSTHandleException($e);
        }
        /**
         * @psalm-suppress LessSpecificReturnStatement
         * @psalm-suppress InvalidReturnStatement
         */
        return match ($response->getStatusCode()) {
            200 => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
            default => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
        };
    }

    /**
     * Enqueue Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     */
    public function enqueueExportLeadsUsingPOSTAsync(
        string $export_id
    ): PromiseInterface {
        return $this->enqueueExportLeadsUsingPOSTAsyncWithHttpInfo($export_id)
            ->then(
                /**
                 * @phpstan-param array{
                 *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
                 *     int,
                 *     array<array<string>>
                 * } $response
                 */
                fn(array $response): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse => $response[0]
            );
    }

    /**
     * Enqueue Export Lead Job
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function enqueueExportLeadsUsingPOSTAsyncWithHttpInfo(
        string $export_id
    ): PromiseInterface {
        return $this->makeAsyncRequest(
            $this->enqueueExportLeadsUsingPOSTRequest($export_id),
            [$this, 'enqueueExportLeadsUsingPOSTHandleException']
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface && $r->getStatusCode() == 200) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        );
    }

    /**
     * Create request for operation 'enqueueExportLeadsUsingPOST'
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function enqueueExportLeadsUsingPOSTRequest(
        string $export_id
    ): Request {
        $resourcePath = '/bulk/v1/leads/export/{exportId}/enqueue.json';
        $resourcePath = str_replace(
            '{' . 'exportId' . '}',
            ObjectSerializer::toPathValue($export_id),
            $resourcePath
        );
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($headers, $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        ));
        $operationHost = $this->config->getHost();

        // figure out header select logic.
        return $this->createRequest(
            'POST',
            $operationHost . $resourcePath,
            // Query.
            [
            ],
            // Headers.
            array_merge(
                [
                ],
                $headers
            ),
            // Form Params
            [
            ],
            ''
        );
    }

    /**
     * Exception handler for getExportLeadsFileUsingGET.
     *
     * @param \NecLimDul\MarketoRest\Lead\ApiException $e
     *   Unprocessed exception.
     *
     * @return \NecLimDul\MarketoRest\Lead\ApiException
     *   Processed exception.
     */
    protected function getExportLeadsFileUsingGETHandleException(ApiException $e): ApiException
    {
        switch ($e->getCode()) {
            case 200:
                /**
                 * Psalm doesn't understand what to do if we're hinting an array.
                 *
                 * @psalm-suppress ArgumentTypeCoercion
                 * @psalm-suppress UndefinedClass
                 * @psalm-suppress ReservedWord
                 */
                $e->setResponseObject(
                    ObjectSerializer::deserialize(
                        $e->getResponseBody() ?? '',
                        'object', // @phpstan-ignore argument.type
                        $e->getResponseHeaders()
                    )
                );
                break;
        }
        return $e;
    }

    /**
     * Get Export Lead File
     *
     * @param string $export_id
     *   Id of export batch job.
     * @param string|null $range
     *   To support partial retrieval of extracted data, the HTTP header \&quot;Range\&quot; of type \&quot;bytes\&quot; may be specified. See RFC 2616 \&quot;Range Retrieval Requests\&quot; for more information. If the header is not set, the entire contents will be returned.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getExportLeadsFileUsingGET(
        string $export_id,
        ?string $range = null
    ): object {
        [$response] = $this->getExportLeadsFileUsingGETWithHttpInfo($export_id, $range);
        return $response;
    }

    /**
     * Get Export Lead File
     *
     * @param string $export_id
     *   Id of export batch job.
     * @param string|null $range
     *   To support partial retrieval of extracted data, the HTTP header \&quot;Range\&quot; of type \&quot;bytes\&quot; may be specified. See RFC 2616 \&quot;Range Retrieval Requests\&quot; for more information. If the header is not set, the entire contents will be returned.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of the response, status code, and headers.
     * @psalm-suppress MoreSpecificReturnType
     * @psalm-suppress InvalidReturnType
     * @phpstan-return array{
     *     object,
     *     int,
     *     array<array<string>>
     * }
     */
    public function getExportLeadsFileUsingGETWithHttpInfo(
        string $export_id,
        ?string $range = null
    ): array {
        $request = $this->getExportLeadsFileUsingGETRequest($export_id, $range);
        try {
            $response = $this->makeRequest($request);
        } catch (ApiException $e) {
            throw $this->getExportLeadsFileUsingGETHandleException($e);
        }
        /**
         * @psalm-suppress LessSpecificReturnStatement
         * @psalm-suppress InvalidReturnStatement
         */
        return match ($response->getStatusCode()) {
            200 => $this->responseToReturn(
                $response,
                'object'
            ),
            default => $this->responseToReturn(
                $response,
                'object'
            ),
        };
    }

    /**
     * Get Export Lead File
     *
     * @param string $export_id
     *   Id of export batch job.
     * @param string|null $range
     *   To support partial retrieval of extracted data, the HTTP header \&quot;Range\&quot; of type \&quot;bytes\&quot; may be specified. See RFC 2616 \&quot;Range Retrieval Requests\&quot; for more information. If the header is not set, the entire contents will be returned.
     *
     * @throws \InvalidArgumentException
     */
    public function getExportLeadsFileUsingGETAsync(
        string $export_id,
        ?string $range = null
    ): PromiseInterface {
        return $this->getExportLeadsFileUsingGETAsyncWithHttpInfo($export_id, $range)
            ->then(
                /**
                 * @phpstan-param array{
                 *     object,
                 *     int,
                 *     array<array<string>>
                 * } $response
                 */
                fn(array $response): object => $response[0]
            );
    }

    /**
     * Get Export Lead File
     *
     * @param string $export_id
     *   Id of export batch job.
     * @param string|null $range
     *   To support partial retrieval of extracted data, the HTTP header \&quot;Range\&quot; of type \&quot;bytes\&quot; may be specified. See RFC 2616 \&quot;Range Retrieval Requests\&quot; for more information. If the header is not set, the entire contents will be returned.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportLeadsFileUsingGETAsyncWithHttpInfo(
        string $export_id,
        ?string $range = null
    ): PromiseInterface {
        return $this->makeAsyncRequest(
            $this->getExportLeadsFileUsingGETRequest($export_id, $range),
            [$this, 'getExportLeadsFileUsingGETHandleException']
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface && $r->getStatusCode() == 200) {
                    $r = $this->responseToReturn(
                        $r,
                        'object'
                    );
                }
                return $r;
            }
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface) {
                    $r = $this->responseToReturn(
                        $r,
                        'object'
                    );
                }
                return $r;
            }
        );
    }

    /**
     * Create request for operation 'getExportLeadsFileUsingGET'
     *
     * @param string $export_id
     *   Id of export batch job.
     * @param string|null $range
     *   To support partial retrieval of extracted data, the HTTP header \&quot;Range\&quot; of type \&quot;bytes\&quot; may be specified. See RFC 2616 \&quot;Range Retrieval Requests\&quot; for more information. If the header is not set, the entire contents will be returned.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getExportLeadsFileUsingGETRequest(
        string $export_id,
        ?string $range = null
    ): Request {
        $resourcePath = '/bulk/v1/leads/export/{exportId}/file.json';
        $resourcePath = str_replace(
            '{' . 'exportId' . '}',
            ObjectSerializer::toPathValue($export_id),
            $resourcePath
        );
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($headers, $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        ));
        $operationHost = $this->config->getHost();

        // figure out header select logic.
        return $this->createRequest(
            'GET',
            $operationHost . $resourcePath,
            // Query.
            [
            ],
            // Headers.
            array_merge(
                [
                    'Range' => isset($range) ? ObjectSerializer::toHeaderValue($range) : null,
                ],
                $headers
            ),
            // Form Params
            [
            ],
            ''
        );
    }

    /**
     * Exception handler for getExportLeadsStatusUsingGET.
     *
     * @param \NecLimDul\MarketoRest\Lead\ApiException $e
     *   Unprocessed exception.
     *
     * @return \NecLimDul\MarketoRest\Lead\ApiException
     *   Processed exception.
     */
    protected function getExportLeadsStatusUsingGETHandleException(ApiException $e): ApiException
    {
        switch ($e->getCode()) {
            case 200:
                $e->setResponseObject(
                    ObjectSerializer::deserialize(
                        $e->getResponseBody() ?? '',
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class,
                        $e->getResponseHeaders()
                    )
                );
                break;
        }
        return $e;
    }

    /**
     * Get Export Lead Job Status
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse
     */
    public function getExportLeadsStatusUsingGET(
        string $export_id
    ): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse {
        [$response] = $this->getExportLeadsStatusUsingGETWithHttpInfo($export_id);
        return $response;
    }

    /**
     * Get Export Lead Job Status
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of the response, status code, and headers.
     * @psalm-suppress MoreSpecificReturnType
     * @psalm-suppress InvalidReturnType
     * @phpstan-return array{
     *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
     *     int,
     *     array<array<string>>
     * }
     */
    public function getExportLeadsStatusUsingGETWithHttpInfo(
        string $export_id
    ): array {
        $request = $this->getExportLeadsStatusUsingGETRequest($export_id);
        try {
            $response = $this->makeRequest($request);
        } catch (ApiException $e) {
            throw $this->getExportLeadsStatusUsingGETHandleException($e);
        }
        /**
         * @psalm-suppress LessSpecificReturnStatement
         * @psalm-suppress InvalidReturnStatement
         */
        return match ($response->getStatusCode()) {
            200 => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
            default => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
            ),
        };
    }

    /**
     * Get Export Lead Job Status
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     */
    public function getExportLeadsStatusUsingGETAsync(
        string $export_id
    ): PromiseInterface {
        return $this->getExportLeadsStatusUsingGETAsyncWithHttpInfo($export_id)
            ->then(
                /**
                 * @phpstan-param array{
                 *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse,
                 *     int,
                 *     array<array<string>>
                 * } $response
                 */
                fn(array $response): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse => $response[0]
            );
    }

    /**
     * Get Export Lead Job Status
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportLeadsStatusUsingGETAsyncWithHttpInfo(
        string $export_id
    ): PromiseInterface {
        return $this->makeAsyncRequest(
            $this->getExportLeadsStatusUsingGETRequest($export_id),
            [$this, 'getExportLeadsStatusUsingGETHandleException']
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface && $r->getStatusCode() == 200) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse::class
                    );
                }
                return $r;
            }
        );
    }

    /**
     * Create request for operation 'getExportLeadsStatusUsingGET'
     *
     * @param string $export_id
     *   Id of export batch job.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getExportLeadsStatusUsingGETRequest(
        string $export_id
    ): Request {
        $resourcePath = '/bulk/v1/leads/export/{exportId}/status.json';
        $resourcePath = str_replace(
            '{' . 'exportId' . '}',
            ObjectSerializer::toPathValue($export_id),
            $resourcePath
        );
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($headers, $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        ));
        $operationHost = $this->config->getHost();

        // figure out header select logic.
        return $this->createRequest(
            'GET',
            $operationHost . $resourcePath,
            // Query.
            [
            ],
            // Headers.
            array_merge(
                [
                ],
                $headers
            ),
            // Form Params
            [
            ],
            ''
        );
    }

    /**
     * Exception handler for getExportLeadsUsingGET.
     *
     * @param \NecLimDul\MarketoRest\Lead\ApiException $e
     *   Unprocessed exception.
     *
     * @return \NecLimDul\MarketoRest\Lead\ApiException
     *   Processed exception.
     */
    protected function getExportLeadsUsingGETHandleException(ApiException $e): ApiException
    {
        switch ($e->getCode()) {
            case 200:
                $e->setResponseObject(
                    ObjectSerializer::deserialize(
                        $e->getResponseBody() ?? '',
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken::class,
                        $e->getResponseHeaders()
                    )
                );
                break;
        }
        return $e;
    }

    /**
     * Get Export Lead Jobs
     *
     * @param string[]|null $status
     *   Comma separated list of statuses to filter on.
     * @param int|null $batch_size
     *   The batch size to return. The max and default value is 300.
     * @param string|null $next_page_token
     *   A token will be returned by this endpoint if the result set is greater than the batch size and can be passed in a subsequent call through this parameter. See Paging Tokens for more info.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken
     */
    public function getExportLeadsUsingGET(
        ?array $status = null,
        ?int $batch_size = null,
        ?string $next_page_token = null
    ): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken {
        [$response] = $this->getExportLeadsUsingGETWithHttpInfo($status, $batch_size, $next_page_token);
        return $response;
    }

    /**
     * Get Export Lead Jobs
     *
     * @param string[]|null $status
     *   Comma separated list of statuses to filter on.
     * @param int|null $batch_size
     *   The batch size to return. The max and default value is 300.
     * @param string|null $next_page_token
     *   A token will be returned by this endpoint if the result set is greater than the batch size and can be passed in a subsequent call through this parameter. See Paging Tokens for more info.
     *
     * @throws \NecLimDul\MarketoRest\Lead\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of the response, status code, and headers.
     * @psalm-suppress MoreSpecificReturnType
     * @psalm-suppress InvalidReturnType
     * @phpstan-return array{
     *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken,
     *     int,
     *     array<array<string>>
     * }
     */
    public function getExportLeadsUsingGETWithHttpInfo(
        ?array $status = null,
        ?int $batch_size = null,
        ?string $next_page_token = null
    ): array {
        $request = $this->getExportLeadsUsingGETRequest($status, $batch_size, $next_page_token);
        try {
            $response = $this->makeRequest($request);
        } catch (ApiException $e) {
            throw $this->getExportLeadsUsingGETHandleException($e);
        }
        /**
         * @psalm-suppress LessSpecificReturnStatement
         * @psalm-suppress InvalidReturnStatement
         */
        return match ($response->getStatusCode()) {
            200 => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken::class
            ),
            default => $this->responseToReturn(
                $response,
                \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken::class
            ),
        };
    }

    /**
     * Get Export Lead Jobs
     *
     * @param string[]|null $status
     *   Comma separated list of statuses to filter on.
     * @param int|null $batch_size
     *   The batch size to return. The max and default value is 300.
     * @param string|null $next_page_token
     *   A token will be returned by this endpoint if the result set is greater than the batch size and can be passed in a subsequent call through this parameter. See Paging Tokens for more info.
     *
     * @throws \InvalidArgumentException
     */
    public function getExportLeadsUsingGETAsync(
        ?array $status = null,
        ?int $batch_size = null,
        ?string $next_page_token = null
    ): PromiseInterface {
        return $this->getExportLeadsUsingGETAsyncWithHttpInfo($status, $batch_size, $next_page_token)
            ->then(
                /**
                 * @phpstan-param array{
                 *     \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken,
                 *     int,
                 *     array<array<string>>
                 * } $response
                 */
                fn(array $response): \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken => $response[0]
            );
    }

    /**
     * Get Export Lead Jobs
     *
     * @param string[]|null $status
     *   Comma separated list of statuses to filter on.
     * @param int|null $batch_size
     *   The batch size to return. The max and default value is 300.
     * @param string|null $next_page_token
     *   A token will be returned by this endpoint if the result set is greater than the batch size and can be passed in a subsequent call through this parameter. See Paging Tokens for more info.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportLeadsUsingGETAsyncWithHttpInfo(
        ?array $status = null,
        ?int $batch_size = null,
        ?string $next_page_token = null
    ): PromiseInterface {
        return $this->makeAsyncRequest(
            $this->getExportLeadsUsingGETRequest($status, $batch_size, $next_page_token),
            [$this, 'getExportLeadsUsingGETHandleException']
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface && $r->getStatusCode() == 200) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken::class
                    );
                }
                return $r;
            }
        )->then(
            function (mixed $r) {
                if ($r instanceof ResponseInterface) {
                    $r = $this->responseToReturn(
                        $r,
                        \NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken::class
                    );
                }
                return $r;
            }
        );
    }

    /**
     * Create request for operation 'getExportLeadsUsingGET'
     *
     * @param string[]|null $status
     *   Comma separated list of statuses to filter on.
     * @param int|null $batch_size
     *   The batch size to return. The max and default value is 300.
     * @param string|null $next_page_token
     *   A token will be returned by this endpoint if the result set is greater than the batch size and can be passed in a subsequent call through this parameter. See Paging Tokens for more info.
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getExportLeadsUsingGETRequest(
        ?array $status = null,
        ?int $batch_size = null,
        ?string $next_page_token = null
    ): Request {
        $resourcePath = '/bulk/v1/leads/export.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($headers, $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        ));
        $operationHost = $this->config->getHost();

        // figure out header select logic.
        return $this->createRequest(
            'GET',
            $operationHost . $resourcePath,
            // Query.
            [
                'status' => isset($status) ? ObjectSerializer::serializeCollection($status, 'multi') : null,
                'batchSize' => isset($batch_size) ? ObjectSerializer::toQueryValue($batch_size) : null,
                'nextPageToken' => isset($next_page_token) ? ObjectSerializer::toQueryValue($next_page_token) : null,
            ],
            // Headers.
            array_merge(
                [
                ],
                $headers
            ),
            // Form Params
            [
            ],
            ''
        );
    }
}
