<?php

/**
 * OpportunitiesApi class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Lead\Api;

// Library Includes
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Psr7\HttpFactory;
use Neclimdul\OpenapiPhp\Helper\Client;
use Neclimdul\OpenapiPhp\Helper\RequestFactory;
use Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface;
use Neclimdul\OpenapiPhp\Helper\Response\ResponseTypeMap;
use Neclimdul\OpenapiPhp\Helper\Serialization\DeserializerInterface;
use Neclimdul\OpenapiPhp\Helper\Serialization\SerializerInterface;
// Package Includes
use NecLimDul\MarketoRest\Lead\Configuration;
use NecLimDul\MarketoRest\Lead\HeaderSelector;
use NecLimDul\MarketoRest\Lead\ObjectSerializer;

/**
 * OpportunitiesApi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.18.0
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
readonly class OpportunitiesApi
{
    /**
     * @param Configuration $config
     *   API Configuration.
     * @param \Neclimdul\OpenapiPhp\Helper\Client $client
     *   Request client.
     * @param \Neclimdul\OpenapiPhp\Helper\RequestFactory<\NecLimDul\MarketoRest\Lead\Model\ModelInterface> $requestFactory
     *   Request factory.
     * @param \Neclimdul\OpenapiPhp\Helper\Serialization\SerializerInterface<\NecLimDul\MarketoRest\Lead\Model\ModelInterface> $serializer
     *   Serialization service.
     */
    public function __construct(
        public Configuration $config,
        private Client $client,
        private RequestFactory $requestFactory,
        private SerializerInterface $serializer,
    ) {
    }

    /**
     * @param (\GuzzleHttp\ClientInterface&\Psr\Http\Client\ClientInterface)|null $client
     *   Request client.
     * @param Configuration|null $config
     *   API Configuration.
     * @param HeaderSelector|null $selector
     *   HeaderSelect helper.
     * @param \Neclimdul\OpenapiPhp\Helper\Serialization\SerializerInterface<\NecLimDul\MarketoRest\Lead\Model\ModelInterface>|null $serializer
     *   Serialization service.
     * @param \Neclimdul\OpenapiPhp\Helper\Serialization\DeserializerInterface|null $deserializer
     *   Deserialization service.
     */
    public static function create(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        ?SerializerInterface $serializer = null,
        ?DeserializerInterface $deserializer = null,
    ): self {
        $serializer = $serializer ?: ObjectSerializer::getDefaultSerializer();
        return new self(
            $config ?: new Configuration(),
            new Client(
                $client ?: new GuzzleClient(),
                $deserializer ?: ObjectSerializer::getDefaultDeserializer(),
            ),
            new RequestFactory(
                new HttpFactory(),
                $serializer,
            ),
            $serializer,
        );
    }

    /**
     * Get current configuration.
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Delete Opportunities
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\DeleteCustomObjectRequest|null $delete_custom_object_request
     *   deleteCustomObjectRequest
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function deleteOpportunitiesUsingPOST(
        null|\NecLimDul\MarketoRest\Lead\Model\DeleteCustomObjectRequest $delete_custom_object_request = null,
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities/delete.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfCustomObject']);

        $request = $this->requestFactory->createRequest(
            'POST',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            $delete_custom_object_request,
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            ['application/json'],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Delete Opportunity Roles
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\DeleteCustomObjectRequest|null $delete_custom_object_request
     *   deleteCustomObjectRequest
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function deleteOpportunityRolesUsingPOST(
        null|\NecLimDul\MarketoRest\Lead\Model\DeleteCustomObjectRequest $delete_custom_object_request = null,
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities/roles/delete.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfCustomObject']);

        $request = $this->requestFactory->createRequest(
            'POST',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            $delete_custom_object_request,
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            ['application/json'],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Describe Opportunity Role
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function describeOpportunityRoleUsingGET(
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities/roles/describe.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfObjectMetaData']);

        $request = $this->requestFactory->createRequest(
            'GET',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            '',
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            [],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Describe Opportunity
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function describeUsingGET4(
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities/describe.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfObjectMetaData']);

        $request = $this->requestFactory->createRequest(
            'GET',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            '',
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            [],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Get Opportunities
     *
     * @param string $filter_type
     *   Opportunities field to filter on
     * @param string[] $filter_values
     *   Comma-separated list of values to match against
     * @param string[]|null $fields
     *   Comma-separated list of fields to include in the response
     * @param int|null $batch_size
     *   Maximum number of records to return in the response. Max and default is 300
     * @param string|null $next_page_token
     *   Paging token returned from a previous response
     * @param \NecLimDul\MarketoRest\Lead\Model\LookupCustomObjectRequest|null $custom_object_lookup_request
     *   customObjectLookupRequest
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function getOpportunitiesUsingGET(
        string $filter_type,
        array $filter_values,
        null|array $fields = null,
        null|int $batch_size = null,
        null|string $next_page_token = null,
        null|\NecLimDul\MarketoRest\Lead\Model\LookupCustomObjectRequest $custom_object_lookup_request = null,
        bool $async = false,
    ): ApiResponseInterface {
        // Verify the required parameter 'filter_values' is set.
        if (empty($filter_values)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filter_values when calling getOpportunitiesUsingGET'
            );
        }
        $resourcePath = '/rest/v1/opportunities.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfCustomObject']);

        $request = $this->requestFactory->createRequest(
            'GET',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            $custom_object_lookup_request,
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            ['application/json'],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Get Opportunity Field by Name
     *
     * @param string $field_api_name
     *   The API name of opportunity field
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function getOpportunityFieldByNameUsingGET(
        string $field_api_name,
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = str_replace(
            [
                '{' . 'fieldApiName' . '}',
            ],
            [
                $this->serializer->toPathValue($field_api_name),
            ],
            '/rest/v1/opportunities/schema/fields/{fieldApiName}.json',
        );
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfLeadField']);

        $request = $this->requestFactory->createRequest(
            'GET',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            '',
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            [],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Get Opportunity Fields
     *
     * @param int|null $batch_size
     *   The batch size to return. The max and default value is 300.
     * @param string|null $next_page_token
     *   A token will be returned by this endpoint if the result set is greater than the batch size and can be passed in a subsequent call through this parameter. See Paging Tokens for more info.
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function getOpportunityFieldsUsingGET(
        null|int $batch_size = null,
        null|string $next_page_token = null,
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities/schema/fields.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfLeadField']);

        $request = $this->requestFactory->createRequest(
            'GET',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            '',
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            [],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Get Opportunity Roles
     *
     * @param string $filter_type
     *   The role field to filter on. Searchable fields can be retrieved with the Describe Opportunity call.
     * @param string[] $filter_values
     *   Comma-separated list of field values to return records for
     * @param string[]|null $fields
     *   Comma-separated list of fields to include in the response
     * @param int|null $batch_size
     *   Maximum number of records to return in the response. Max and default is 300
     * @param string|null $next_page_token
     *   Paging token returned from a previous response
     * @param \NecLimDul\MarketoRest\Lead\Model\LookupCustomObjectRequest|null $custom_object_lookup_request
     *   Optional JSON request for retrieving opportunity roles with compound keys
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function getOpportunityRolesUsingGET(
        string $filter_type,
        array $filter_values,
        null|array $fields = null,
        null|int $batch_size = null,
        null|string $next_page_token = null,
        null|\NecLimDul\MarketoRest\Lead\Model\LookupCustomObjectRequest $custom_object_lookup_request = null,
        bool $async = false,
    ): ApiResponseInterface {
        // Verify the required parameter 'filter_values' is set.
        if (empty($filter_values)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filter_values when calling getOpportunityRolesUsingGET'
            );
        }
        $resourcePath = '/rest/v1/opportunities/roles.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfCustomObject']);

        $request = $this->requestFactory->createRequest(
            'GET',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            $custom_object_lookup_request,
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            ['application/json'],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Sync Opportunities
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\SyncCustomObjectRequest $sync_custom_object_request
     *   syncCustomObjectRequest
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function syncOpportunitiesUsingPOST(
        \NecLimDul\MarketoRest\Lead\Model\SyncCustomObjectRequest $sync_custom_object_request,
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfCustomObject']);

        $request = $this->requestFactory->createRequest(
            'POST',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            $sync_custom_object_request,
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            ['application/json'],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }

    /**
     * Sync Opportunity Roles
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\SyncCustomObjectRequest $sync_custom_object_request
     *   syncCustomObjectRequest
     * @param bool $async
     *   Set to true to make an async request.
     *
     * @throws \InvalidArgumentException
     * @return \Neclimdul\OpenapiPhp\Helper\Response\ApiResponseInterface
     */
    public function syncOpportunityRolesUsingPOST(
        \NecLimDul\MarketoRest\Lead\Model\SyncCustomObjectRequest $sync_custom_object_request,
        bool $async = false,
    ): ApiResponseInterface {
        $resourcePath = '/rest/v1/opportunities/roles.json';
        $headers = [];
        if ($this->config->getUserAgent()) {
            $headers['User-Agent'] = $this->config->getUserAgent();
        }

        $responseMap = new ResponseTypeMap([]);
        $responseMap->setSchema('200', 'application/json', ['type' => '\NecLimDul\MarketoRest\Lead\Model\ResponseOfCustomObject']);

        $request = $this->requestFactory->createRequest(
            'POST',
            $this->config->getHost() . $resourcePath,
            // Query.
            [],
            $headers,
            [],
            $sync_custom_object_request,
        );
        $request = $this->requestFactory->attachAcceptHeader(
            $request,
            ['application/json'],
            ['application/json'],
        );

        return $this->client->makeRequest(
            $request,
            $responseMap,
            async: $async,
        );
    }
}
