<?php

/**
 * CloneNewAsset class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Model;

use Neclimdul\OpenapiPhp\Helper\Model\ModelBase;
use Neclimdul\OpenapiPhp\Helper\Model\AdditionalPropertiesTrait;
use Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait;
use Neclimdul\OpenapiPhp\Helper\Model\OpenApiAttributesTrait;
use NecLimDul\MarketoRest\Asset\ObjectSerializer;

/**
 * CloneNewAsset
 *
 * The version of the OpenAPI document: 1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.21.0
 *
 * @phpstan-type CloneNewAssetArray array{
 *     name: string,
 *     description?: ?string,
 * }
 *
 * @method string getName()
 * @method CloneNewAsset setName(string $name)
 * @method string|null getDescription()
 * @method CloneNewAsset setDescription(string|null $description)
 *
 * @extends \Neclimdul\OpenapiPhp\Helper\Model\ModelBase<CloneNewAssetArray>
 * @implements \ArrayAccess<key-of<CloneNewAssetArray>, value-of<CloneNewAssetArray>>
 * @psalm-suppress MixedReturnStatement
 * @psalm-suppress MixedInferredReturnType
 */
class CloneNewAsset extends ModelBase implements ModelInterface, \ArrayAccess, \JsonSerializable, \Stringable
{
    use OpenApiAttributesTrait;
    use AdditionalPropertiesTrait;

    /**
     * @use \Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait<CloneNewAssetArray>
     */
    use ArrayAccessTrait;

    public const ?string DISCRIMINATOR = null;

    /**
     * {@inheritDoc}
     */
    protected static string $openAPIModelName = 'CloneNewAsset';

    /**
     * {@inheritDoc}
     */
    protected static array $openApiAttributes = [
        'type' => [
            'name' => 'string',
            'description' => 'string',
        ],
        'required' => [
            'name' => 'name',
        ],
        'format' => [
        ],
        'map' => [
            'name' => 'name',
            'description' => 'description',
        ],
        'setter' => [
            'name' => 'setName',
            'description' => 'setDescription',
        ],
        'getter' => [
            'name' => 'getName',
            'description' => 'getDescription',
        ],
    ];

    /**
     * Constructor
     *
     * @param CloneNewAssetArray $data
     *   Associated array of property values initializing the model.
     */
    public function __construct(array $data)
    {
        parent::__construct($data);
    }

    #[\Override]
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * {@inheritDoc}
     */
    #[\ReturnTypeWillChange]
    #[\Override]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
        );
    }
}
