<?php

/**
 * ResponseOfFolderResponse class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Model;

use Neclimdul\OpenapiPhp\Helper\Model\ModelBase;
use Neclimdul\OpenapiPhp\Helper\Model\AdditionalPropertiesTrait;
use Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait;
use Neclimdul\OpenapiPhp\Helper\Model\OpenApiAttributesTrait;
use NecLimDul\MarketoRest\Asset\ObjectSerializer;

/**
 * ResponseOfFolderResponse
 *
 * The version of the OpenAPI document: 1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.18.0
 *
 * @phpstan-type ResponseOfFolderResponseArray array{
 *     errors?: ?\NecLimDul\MarketoRest\Asset\Model\Error[],
 *     request_id?: ?string,
 *     result?: ?\NecLimDul\MarketoRest\Asset\Model\FolderResponse[],
 *     success?: ?bool,
 *     warnings?: ?string[],
 * }
 *
 * @method \NecLimDul\MarketoRest\Asset\Model\Error[]|null getErrors()
 * @method ResponseOfFolderResponse setErrors(\NecLimDul\MarketoRest\Asset\Model\Error[]|null $errors)
 * @method string|null getRequestId()
 * @method ResponseOfFolderResponse setRequestId(string|null $request_id)
 * @method \NecLimDul\MarketoRest\Asset\Model\FolderResponse[]|null getResult()
 * @method ResponseOfFolderResponse setResult(\NecLimDul\MarketoRest\Asset\Model\FolderResponse[]|null $result)
 * @method bool|null getSuccess()
 * @method ResponseOfFolderResponse setSuccess(bool|null $success)
 * @method string[]|null getWarnings()
 * @method ResponseOfFolderResponse setWarnings(string[]|null $warnings)
 *
 * @extends \Neclimdul\OpenapiPhp\Helper\Model\ModelBase<ResponseOfFolderResponseArray>
 * @implements \ArrayAccess<key-of<ResponseOfFolderResponseArray>, value-of<ResponseOfFolderResponseArray>>
 * @psalm-suppress MixedReturnStatement
 * @psalm-suppress MixedInferredReturnType
 */
class ResponseOfFolderResponse extends ModelBase implements ModelInterface, \ArrayAccess, \JsonSerializable, \Stringable
{
    use OpenApiAttributesTrait;
    use AdditionalPropertiesTrait;

    /**
     * @use \Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait<ResponseOfFolderResponseArray>
     */
    use ArrayAccessTrait;

    public const ?string DISCRIMINATOR = null;

    /**
     * {@inheritDoc}
     */
    protected static string $openAPIModelName = 'ResponseOfFolderResponse';

    /**
     * {@inheritDoc}
     */
    protected static array $openApiAttributes = [
        'type' => [
            'errors' => '\NecLimDul\MarketoRest\Asset\Model\Error[]',
            'request_id' => 'string',
            'result' => '\NecLimDul\MarketoRest\Asset\Model\FolderResponse[]',
            'success' => 'bool',
            'warnings' => 'string[]',
        ],
        'required' => [
        ],
        'format' => [
        ],
        'map' => [
            'errors' => 'errors',
            'request_id' => 'requestId',
            'result' => 'result',
            'success' => 'success',
            'warnings' => 'warnings',
        ],
        'setter' => [
            'errors' => 'setErrors',
            'request_id' => 'setRequestId',
            'result' => 'setResult',
            'success' => 'setSuccess',
            'warnings' => 'setWarnings',
        ],
        'getter' => [
            'errors' => 'getErrors',
            'request_id' => 'getRequestId',
            'result' => 'getResult',
            'success' => 'getSuccess',
            'warnings' => 'getWarnings',
        ],
    ];

    /**
     * Constructor
     *
     * @param ResponseOfFolderResponseArray $data
     *   Associated array of property values initializing the model.
     */
    public function __construct(array $data = [])
    {
        parent::__construct($data);
    }

    #[\Override]
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * {@inheritDoc}
     */
    #[\ReturnTypeWillChange]
    #[\Override]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
        );
    }
}
