<?php

/**
 * SmartListResponseWithRules
 *
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT

 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Asset
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NecLimDul\MarketoRest\Asset\Model;

use ArrayAccess;
use Neclimdul\OpenapiPhp\Helper\Model\ModelBase;
use Neclimdul\OpenapiPhp\Helper\Model\AdditionalPropertiesTrait;
use Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait;
use NecLimDul\MarketoRest\Asset\ObjectSerializer;

/**
 * SmartListResponseWithRules Class Doc Comment
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Asset
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<?string, ?mixed>
 * @psalm-suppress MixedReturnStatement
 * @psalm-suppress MixedInferredReturnType
 */
class SmartListResponseWithRules extends ModelBase implements ModelInterface, ArrayAccess, \JsonSerializable
{
    use AdditionalPropertiesTrait;

    /**
    * @use \Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait<string, ?mixed>
    */
    use ArrayAccessTrait;

    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SmartListResponseWithRules';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|class-string>
      * @psalm-var array<string, string|class-string>
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'description' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'url' => 'string',
        'folder' => '\NecLimDul\MarketoRest\Asset\Model\Folder',
        'workspace' => 'string',
        'rules' => '\NecLimDul\MarketoRest\Asset\Model\SmartListRules',
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'description' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'url' => null,
        'folder' => null,
        'workspace' => null,
        'rules' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'url' => 'url',
        'folder' => 'folder',
        'workspace' => 'workspace',
        'rules' => 'rules',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'url' => 'setUrl',
        'folder' => 'setFolder',
        'workspace' => 'setWorkspace',
        'rules' => 'setRules',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'url' => 'getUrl',
        'folder' => 'getFolder',
        'workspace' => 'getWorkspace',
        'rules' => 'getRules',
    ];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = [])
    {
        $this->container = $this->collectAttributeValues($data);
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties['id'] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties['name'] = "'name' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties['description'] = "'description' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties['created_at'] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties['updated_at'] = "'updated_at' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties['url'] = "'url' can't be null";
        }
        if ($this->container['folder'] === null) {
            $invalidProperties['folder'] = "'folder' can't be null";
        }
        if ($this->container['workspace'] === null) {
            $invalidProperties['workspace'] = "'workspace' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Id of the smart list
     *
     * @return self
     */
    public function setId(int $id): SmartListResponseWithRules
    {
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the smart list
     *
     * @return self
     */
    public function setName(string $name): SmartListResponseWithRules
    {
        $this->container['name'] = $name;

        return $this;
    }
    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription(): string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Description of the smart list
     *
     * @return self
     */
    public function setDescription(string $description): SmartListResponseWithRules
    {
        $this->container['description'] = $description;

        return $this;
    }
    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Datetime the smart list was created
     *
     * @return self
     */
    public function setCreatedAt(\DateTime $created_at): SmartListResponseWithRules
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }
    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at Datetime the smart list was most recently updated
     *
     * @return self
     */
    public function setUpdatedAt(\DateTime $updated_at): SmartListResponseWithRules
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl(): string
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url Url of the smart list in the Marketo UI
     *
     * @return self
     */
    public function setUrl(string $url): SmartListResponseWithRules
    {
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Gets folder
     *
     * @return \NecLimDul\MarketoRest\Asset\Model\Folder
     */
    public function getFolder(): \NecLimDul\MarketoRest\Asset\Model\Folder
    {
        return $this->container['folder'];
    }

    /**
     * Sets folder
     *
     * @param \NecLimDul\MarketoRest\Asset\Model\Folder $folder folder
     *
     * @return self
     */
    public function setFolder(\NecLimDul\MarketoRest\Asset\Model\Folder $folder): SmartListResponseWithRules
    {
        $this->container['folder'] = $folder;

        return $this;
    }
    /**
     * Gets workspace
     *
     * @return string
     */
    public function getWorkspace(): string
    {
        return $this->container['workspace'];
    }

    /**
     * Sets workspace
     *
     * @param string $workspace Name of the workspace
     *
     * @return self
     */
    public function setWorkspace(string $workspace): SmartListResponseWithRules
    {
        $this->container['workspace'] = $workspace;

        return $this;
    }
    /**
     * Gets rules
     *
     * @return \NecLimDul\MarketoRest\Asset\Model\SmartListRules|null
     */
    public function getRules(): ?\NecLimDul\MarketoRest\Asset\Model\SmartListRules
    {
        return $this->container['rules'];
    }

    /**
     * Sets rules
     *
     * @param \NecLimDul\MarketoRest\Asset\Model\SmartListRules|null $rules rules
     *
     * @return self
     */
    public function setRules(?\NecLimDul\MarketoRest\Asset\Model\SmartListRules $rules): SmartListResponseWithRules
    {
        $this->container['rules'] = $rules;

        return $this;
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     * @throws \JsonException
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
        );
    }
}
