<?php

/**
 * ErrorsData class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Lead\Model;

use Neclimdul\OpenapiPhp\Helper\Model\ModelBase;
use Neclimdul\OpenapiPhp\Helper\Model\AdditionalPropertiesTrait;
use Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait;
use Neclimdul\OpenapiPhp\Helper\Model\OpenApiAttributesTrait;
use NecLimDul\MarketoRest\Lead\ObjectSerializer;

/**
 * ErrorsData
 *
 * The version of the OpenAPI document: 1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.18.0
 *
 * @phpstan-type ErrorsDataArray array{
 *     date: \DateTime,
 *     errors?: ?\NecLimDul\MarketoRest\Lead\Model\ErrorCount[],
 *     total?: ?int,
 * }
 * @extends \Neclimdul\OpenapiPhp\Helper\Model\ModelBase<ErrorsDataArray>
 * @implements \ArrayAccess<key-of<ErrorsDataArray>, value-of<ErrorsDataArray>>
 * @psalm-suppress MixedReturnStatement
 * @psalm-suppress MixedInferredReturnType
 */
class ErrorsData extends ModelBase implements ModelInterface, \ArrayAccess, \JsonSerializable, \Stringable
{
    use OpenApiAttributesTrait;
    use AdditionalPropertiesTrait;

    /**
     * @use \Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait<ErrorsDataArray>
     */
    use ArrayAccessTrait;

    public const ?string DISCRIMINATOR = null;

    /**
     * {@inheritDoc}
     */
    protected static string $openAPIModelName = 'ErrorsData';

    /**
     * {@inheritDoc}
     */
    protected static array $openApiAttributes = [
        'type' => [
            'date' => '\DateTime',
            'errors' => '\NecLimDul\MarketoRest\Lead\Model\ErrorCount[]',
            'total' => 'int',
        ],
        'required' => [
            'date' => 'date',
        ],
        'format' => [
            'date' => 'date-time',
            'total' => 'int32',
        ],
        'map' => [
            'date' => 'date',
            'errors' => 'errors',
            'total' => 'total',
        ],
        'setter' => [
            'date' => 'setDate',
            'errors' => 'setErrors',
            'total' => 'setTotal',
        ],
        'getter' => [
            'date' => 'getDate',
            'errors' => 'getErrors',
            'total' => 'getTotal',
        ],
    ];

    /**
     * Constructor
     *
     * @param ErrorsDataArray $data
     *   Associated array of property values initializing the model.
     */
    public function __construct(array $data)
    {
        parent::__construct($data);
    }

    #[\Override]
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    #[\Override]
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets date
     *
     * @return \DateTime
     */
    public function getDate(): \DateTime
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime $date Date of the collected calls
     *
     * @return self
     */
    public function setDate(\DateTime $date): ErrorsData
    {
        $this->container['date'] = $date;

        return $this;
    }
    /**
     * Gets errors
     *
     * @return \NecLimDul\MarketoRest\Lead\Model\ErrorCount[]|null
     */
    public function getErrors(): ?array
    {
        return $this->container['errors'] ?? null;
    }

    /**
     * Sets errors
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ErrorCount[]|null $errors Counts for individual error codes
     *
     * @return self
     */
    public function setErrors(?array $errors): ErrorsData
    {
        $this->container['errors'] = $errors;

        return $this;
    }
    /**
     * Gets total
     *
     * @return int|null
     */
    public function getTotal(): ?int
    {
        return $this->container['total'] ?? null;
    }

    /**
     * Sets total
     *
     * @param int|null $total Total number of errors in the time period
     *
     * @return self
     */
    public function setTotal(?int $total): ErrorsData
    {
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * {@inheritDoc}
     */
    #[\ReturnTypeWillChange]
    #[\Override]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
        );
    }
}
