<?php

/**
 * ResponseOfImportProgramMemberResponse
 *
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.8.0-SNAPSHOT

 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NecLimDul\MarketoRest\Lead\Model;

use ArrayAccess;
use Neclimdul\OpenapiPhp\Helper\Model\ModelBase;
use Neclimdul\OpenapiPhp\Helper\Model\AdditionalPropertiesTrait;
use Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait;
use NecLimDul\MarketoRest\Lead\ObjectSerializer;

/**
 * ResponseOfImportProgramMemberResponse Class Doc Comment
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<?string, ?mixed>
 * @psalm-suppress MixedReturnStatement
 * @psalm-suppress MixedInferredReturnType
 */
class ResponseOfImportProgramMemberResponse extends ModelBase implements ModelInterface, ArrayAccess, \JsonSerializable
{
    use AdditionalPropertiesTrait;

    /**
     * @use \Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait<string, ?mixed>
     */
    use ArrayAccessTrait;

    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ResponseOfImportProgramMemberResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|class-string>
     * @psalm-var array<string, string|class-string>
     */
    protected static $openAPITypes = [
        'errors' => '\NecLimDul\MarketoRest\Lead\Model\Error[]',
        'request_id' => 'string',
        'result' => '\NecLimDul\MarketoRest\Lead\Model\ImportProgramMemberResponse[]',
        'success' => 'bool',
        'warnings' => '\NecLimDul\MarketoRest\Lead\Model\Warning[]',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'errors' => null,
        'request_id' => null,
        'result' => null,
        'success' => null,
        'warnings' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'errors' => 'errors',
        'request_id' => 'requestId',
        'result' => 'result',
        'success' => 'success',
        'warnings' => 'warnings',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'errors' => 'setErrors',
        'request_id' => 'setRequestId',
        'result' => 'setResult',
        'success' => 'setSuccess',
        'warnings' => 'setWarnings',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'errors' => 'getErrors',
        'request_id' => 'getRequestId',
        'result' => 'getResult',
        'success' => 'getSuccess',
        'warnings' => 'getWarnings',
    ];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = [])
    {
        $this->container = $this->collectAttributeValues($data);
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['errors'] === null) {
            $invalidProperties['errors'] = "'errors' can't be null";
        }
        if ($this->container['request_id'] === null) {
            $invalidProperties['request_id'] = "'request_id' can't be null";
        }
        if ($this->container['result'] === null) {
            $invalidProperties['result'] = "'result' can't be null";
        }
        if ($this->container['success'] === null) {
            $invalidProperties['success'] = "'success' can't be null";
        }
        if ($this->container['warnings'] === null) {
            $invalidProperties['warnings'] = "'warnings' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets errors
     *
     * @return \NecLimDul\MarketoRest\Lead\Model\Error[]
     */
    public function getErrors(): array
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\Error[] $errors Array of errors that occurred if the request was unsuccessful
     *
     * @return self
     */
    public function setErrors(array $errors): ResponseOfImportProgramMemberResponse
    {
        $this->container['errors'] = $errors;

        return $this;
    }
    /**
     * Gets request_id
     *
     * @return string
     */
    public function getRequestId(): string
    {
        return $this->container['request_id'];
    }

    /**
     * Sets request_id
     *
     * @param string $request_id Id of the request made
     *
     * @return self
     */
    public function setRequestId(string $request_id): ResponseOfImportProgramMemberResponse
    {
        $this->container['request_id'] = $request_id;

        return $this;
    }
    /**
     * Gets result
     *
     * @return \NecLimDul\MarketoRest\Lead\Model\ImportProgramMemberResponse[]
     */
    public function getResult(): array
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\ImportProgramMemberResponse[] $result Array of results for individual records in the operation, may be empty
     *
     * @return self
     */
    public function setResult(array $result): ResponseOfImportProgramMemberResponse
    {
        $this->container['result'] = $result;

        return $this;
    }
    /**
     * Gets success
     *
     * @return bool
     */
    public function getSuccess(): bool
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     *
     * @param bool $success Whether the request succeeded
     *
     * @return self
     */
    public function setSuccess(bool $success): ResponseOfImportProgramMemberResponse
    {
        $this->container['success'] = $success;

        return $this;
    }
    /**
     * Gets warnings
     *
     * @return \NecLimDul\MarketoRest\Lead\Model\Warning[]
     */
    public function getWarnings(): array
    {
        return $this->container['warnings'];
    }

    /**
     * Sets warnings
     *
     * @param \NecLimDul\MarketoRest\Lead\Model\Warning[] $warnings Array of warnings given for the operation
     *
     * @return self
     */
    public function setWarnings(array $warnings): ResponseOfImportProgramMemberResponse
    {
        $this->container['warnings'] = $warnings;

        return $this;
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     * @throws \JsonException
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
        );
    }
}
