<?php

/**
 * SalesPerson class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Lead\Model;

use Neclimdul\OpenapiPhp\Helper\Model\ModelBase;
use Neclimdul\OpenapiPhp\Helper\Model\AdditionalPropertiesTrait;
use Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait;
use Neclimdul\OpenapiPhp\Helper\Model\OpenApiAttributesTrait;
use NecLimDul\MarketoRest\Lead\ObjectSerializer;

/**
 * SalesPerson
 *
 * The version of the OpenAPI document: 1.0
 * Contact:
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.21.0
 *
 * @phpstan-type SalesPersonArray array{
 *     id?: ?int,
 *     reasons?: ?\NecLimDul\MarketoRest\Lead\Model\Reason[],
 *     seq?: ?int,
 *     status?: ?string,
 * }
 *
 * @method int|null getId()
 * @method SalesPerson setId(int|null $id)
 * @method \NecLimDul\MarketoRest\Lead\Model\Reason[]|null getReasons()
 * @method SalesPerson setReasons(\NecLimDul\MarketoRest\Lead\Model\Reason[]|null $reasons)
 * @method int|null getSeq()
 * @method SalesPerson setSeq(int|null $seq)
 * @method string|null getStatus()
 * @method SalesPerson setStatus(string|null $status)
 *
 * @extends \Neclimdul\OpenapiPhp\Helper\Model\ModelBase<SalesPersonArray>
 * @implements \ArrayAccess<key-of<SalesPersonArray>, value-of<SalesPersonArray>>
 * @psalm-suppress MixedReturnStatement
 * @psalm-suppress MixedInferredReturnType
 */
class SalesPerson extends ModelBase implements ModelInterface, \ArrayAccess, \JsonSerializable, \Stringable
{
    use OpenApiAttributesTrait;
    use AdditionalPropertiesTrait;

    /**
     * @use \Neclimdul\OpenapiPhp\Helper\Model\ArrayAccessTrait<SalesPersonArray>
     */
    use ArrayAccessTrait;

    public const ?string DISCRIMINATOR = null;
    public const STATUS_CREATED = 'created';
    public const STATUS_UPDATED = 'updated';
    public const STATUS_DELETED = 'deleted';
    public const STATUS_SKIPPED = 'skipped';
    public const STATUS_ADDED = 'added';
    public const STATUS_REMOVED = 'removed';

    /**
     * {@inheritDoc}
     */
    protected static string $openAPIModelName = 'SalesPerson';

    /**
     * {@inheritDoc}
     */
    protected static array $openApiAttributes = [
        'type' => [
            'id' => 'int',
            'reasons' => '\NecLimDul\MarketoRest\Lead\Model\Reason[]',
            'seq' => 'int',
            'status' => 'string',
        ],
        'required' => [
        ],
        'format' => [
            'id' => 'int64',
            'seq' => 'int32',
        ],
        'map' => [
            'id' => 'id',
            'reasons' => 'reasons',
            'seq' => 'seq',
            'status' => 'status',
        ],
        'setter' => [
            'id' => 'setId',
            'reasons' => 'setReasons',
            'seq' => 'setSeq',
            'status' => 'setStatus',
        ],
        'getter' => [
            'id' => 'getId',
            'reasons' => 'getReasons',
            'seq' => 'getSeq',
            'status' => 'getStatus',
        ],
    ];

    /**
     * Constructor
     *
     * @param SalesPersonArray $data
     *   Associated array of property values initializing the model.
     */
    public function __construct(array $data = [])
    {
        parent::__construct($data);
    }

    #[\Override]
    public function listInvalidProperties(): array
    {
        $invalidProperties = parent::listInvalidProperties();
        $allowedValues = $this->getStatusAllowableValues();
        if (
            isset($this->container['status'])
            && !in_array($this->container['status'], $allowedValues, true)
        ) {
            $invalidProperties['status'] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getStatusAllowableValues(): array
    {
        return [
            self::STATUS_CREATED,
            self::STATUS_UPDATED,
            self::STATUS_DELETED,
            self::STATUS_SKIPPED,
            self::STATUS_ADDED,
            self::STATUS_REMOVED,
        ];
    }

    /**
     * {@inheritDoc}
     */
    #[\ReturnTypeWillChange]
    #[\Override]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * {@inheritDoc}
     */
    #[\Override]
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
        );
    }
}
