<?php

/**
 * LandingPageRedirectRulesApiTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

declare(strict_types=1);

namespace NecLimDul\MarketoRest\Asset\Test\Api;

use NecLimDul\MarketoRest\Asset\ApiException;
use NecLimDul\MarketoRest\Asset\Configuration;
use NecLimDul\MarketoRest\Asset\Api\LandingPageRedirectRulesApi;
use Neclimdul\OpenapiPhpTesting\ApiAssertionsTrait;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use Faker\Generator;
use Faker\Factory as FakerFactory;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use Prophecy\PhpUnit\ProphecyTrait;

/**
 * LandingPageRedirectRulesApiTest
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.18.0
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Asset
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
#[CoversClass(LandingPageRedirectRulesApi::class)]
class LandingPageRedirectRulesApiTest extends TestCase
{
    use ApiAssertionsTrait;
    use FakeValuesTrait;
    use ProphecyTrait;

    private LandingPageRedirectRulesApi $sot;

    private Generator $faker;

    private MockHandler $mockHandler;

    /**
     * @var \GuzzleHttp\Client
     */
    private GuzzleClient $client;

    public function __construct(
        ?string $name = null,
        array $data = [],
        $dataName = ''
    ) {
        parent::__construct($name, $data, $dataName);
        // Ensure this is setup for provider.
        $this->setFaker(FakerFactory::create());
        $this->setAssertedApiException(ApiException::class);
    }

    public function setUp(): void
    {
        parent::setUp();
        $this->faker = FakerFactory::create();
        $this->mockHandler = new MockHandler();
        $this->client = new GuzzleClient(['handler' => HandlerStack::create($this->mockHandler)]);
        $this->sot = LandingPageRedirectRulesApi::create($this->client);
        $this->setAssertedApiException(ApiException::class);
        // Add a key, so we can assert its included.
        $this->sot->getConfig()->setApiKey('Authorization', 'secure-key');
    }

    /**
     * @legacy-covers ::getConfig
     */
    public function testGetConfig(): void
    {
        $this->assertInstanceOf(Configuration::class, $this->sot->getConfig());
        $config = new Configuration();
        $sot = LandingPageRedirectRulesApi::create($this->client, $config);
        $this->assertSame($config, $sot->getConfig());
    }

    public static function provideCreateLandingPageRedirectRuleUsingPOST(): \Generator
    {
        yield from static::provideFakeRequests(
            '200',
            [
                'string',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectFrom',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectTo',
            ],
            '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectFrom',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectTo',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectFrom',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectTo',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @legacy-covers ::createLandingPageRedirectRuleUsingPOST
     */
    #[DataProvider('provideCreateLandingPageRedirectRuleUsingPOST')]
    public function testCreateLandingPageRedirectRuleUsingPOST(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'createLandingPageRedirectRuleUsingPOST'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideDeleteLandingPageRedirectRuleUsingPOST(): \Generator
    {
        yield from static::provideFakeRequests(
            '200',
            [
                'int',
            ],
            '\NecLimDul\MarketoRest\Asset\Model\ResponseOfIdResponse',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'int',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'int',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @legacy-covers ::deleteLandingPageRedirectRuleUsingPOST
     */
    #[DataProvider('provideDeleteLandingPageRedirectRuleUsingPOST')]
    public function testDeleteLandingPageRedirectRuleUsingPOST(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Asset\Model\ResponseOfIdResponse') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'deleteLandingPageRedirectRuleUsingPOST'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideGetLandingPageDomainsUsingGET(): \Generator
    {
        yield from static::provideFakeRequests(
            '200',
            [
                'int',
                'int',
            ],
            '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageDomains',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'int',
                'int',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'int',
                'int',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @legacy-covers ::getLandingPageDomainsUsingGET
     */
    #[DataProvider('provideGetLandingPageDomainsUsingGET')]
    public function testGetLandingPageDomainsUsingGET(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageDomains') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'getLandingPageDomainsUsingGET'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideGetLandingPageRedirectRuleByIdUsingGET(): \Generator
    {
        yield from static::provideFakeRequests(
            '200',
            [
                'int',
            ],
            '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'int',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'int',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @legacy-covers ::getLandingPageRedirectRuleByIdUsingGET
     */
    #[DataProvider('provideGetLandingPageRedirectRuleByIdUsingGET')]
    public function testGetLandingPageRedirectRuleByIdUsingGET(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'getLandingPageRedirectRuleByIdUsingGET'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideGetLandingPageRedirectRulesUsingGET(): \Generator
    {
        yield from static::provideFakeRequests(
            '200',
            [
                'int',
                'int',
                'string',
                'string',
                'string',
                'string',
            ],
            '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'int',
                'int',
                'string',
                'string',
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'int',
                'int',
                'string',
                'string',
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @legacy-covers ::getLandingPageRedirectRulesUsingGET
     */
    #[DataProvider('provideGetLandingPageRedirectRulesUsingGET')]
    public function testGetLandingPageRedirectRulesUsingGET(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'getLandingPageRedirectRulesUsingGET'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideUpdateLandingPageRedirectRuleUsingPOST(): \Generator
    {
        yield from static::provideFakeRequests(
            '200',
            [
                'int',
                'string',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectFrom',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectTo',
            ],
            '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'int',
                'string',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectFrom',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectTo',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'int',
                'string',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectFrom',
                '\NecLimDul\MarketoRest\Asset\Model\RedirectTo',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @legacy-covers ::updateLandingPageRedirectRuleUsingPOST
     */
    #[DataProvider('provideUpdateLandingPageRedirectRuleUsingPOST')]
    public function testUpdateLandingPageRedirectRuleUsingPOST(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Asset\Model\ResponseOfLandingPageRedirectRules') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'updateLandingPageRedirectRuleUsingPOST'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }
}
