<?php

/**
 * BulkExportCustomObjectsApiTest class file.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace NecLimDul\MarketoRest\Lead\Test\Api;

use NecLimDul\MarketoRest\Lead\ApiException;
use NecLimDul\MarketoRest\Lead\Configuration;
use NecLimDul\MarketoRest\Lead\Api\BulkExportCustomObjectsApi;
use Neclimdul\OpenapiPhpTesting\ApiAssertionsTrait;
use Neclimdul\OpenapiPhpTesting\FakeValuesTrait;
use Faker\Generator;
use Faker\Factory as FakerFactory;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use PHPUnit\Framework\TestCase;
use Prophecy\PhpUnit\ProphecyTrait;

/**
 * BulkExportCustomObjectsApiTest
 *
 * The version of the OpenAPI document: 1.0
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.13.0
 *
 * @category Class
 * @package  NecLimDul\MarketoRest\Lead
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @coversDefaultClass \NecLimDul\MarketoRest\Lead\Api\BulkExportCustomObjectsApi
 */
class BulkExportCustomObjectsApiTest extends TestCase
{
    use ApiAssertionsTrait;
    use FakeValuesTrait;
    use ProphecyTrait;

    private BulkExportCustomObjectsApi $sot;

    private Generator $faker;

    private MockHandler $mockHandler;

    /**
     * @var \GuzzleHttp\Client
     */
    private GuzzleClient $client;

    public function __construct(
        ?string $name = null,
        array $data = [],
        $dataName = ''
    ) {
        parent::__construct($name, $data, $dataName);
        // Ensure this is setup for provider.
        $this->setFaker(FakerFactory::create());
        $this->setAssertedApiException(ApiException::class);
    }

    public function setUp(): void
    {
        parent::setUp();
        $this->faker = FakerFactory::create();
        $this->mockHandler = new MockHandler();
        $this->client = new GuzzleClient(['handler' => HandlerStack::create($this->mockHandler)]);
        $this->sot = new BulkExportCustomObjectsApi($this->client);
        $this->setAssertedApiException(ApiException::class);
        // Add a key, so we can assert its included.
        $this->sot->getConfig()->setApiKey('Authorization', 'secure-key');
    }

    /**
     * @covers ::setHostIndex
     * @covers ::getHostIndex
     */
    public function testHostIndex(): void
    {
        $this->assertEquals(0, $this->sot->getHostIndex());
        $sot = new BulkExportCustomObjectsApi($this->client, null, null, 5);
        $this->assertEquals(5, $sot->getHostIndex());
        $sot->setHostIndex(6);
        $this->assertEquals(6, $sot->getHostIndex());
        $sot->setHostIndex(0);
        $this->assertEquals(0, $sot->getHostIndex());
    }

    /**
     * @covers ::getConfig
     */
    public function testGetConfig(): void
    {
        $this->assertInstanceOf(Configuration::class, $this->sot->getConfig());
        $config = new Configuration();
        $sot = new BulkExportCustomObjectsApi($this->client, $config, null, 5);
        $this->assertSame($config, $sot->getConfig());
    }

    public static function provideCancelExportCustomObjectsUsingPOST(): \Generator
    {
        yield from static::provideFakeRequests(
            200,
            [
                'string',
                'string',
            ],
            '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @dataProvider provideCancelExportCustomObjectsUsingPOST
     * @covers ::cancelExportCustomObjectsUsingPOST
     */
    public function testCancelExportCustomObjectsUsingPOST(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'cancelExportCustomObjectsUsingPOST'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideCreateExportCustomObjectsUsingPOST(): \Generator
    {
        yield from static::provideFakeRequests(
            200,
            [
                'string',
                '\NecLimDul\MarketoRest\Lead\Model\ExportCustomObjectRequest',
            ],
            '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                '\NecLimDul\MarketoRest\Lead\Model\ExportCustomObjectRequest',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                '\NecLimDul\MarketoRest\Lead\Model\ExportCustomObjectRequest',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @dataProvider provideCreateExportCustomObjectsUsingPOST
     * @covers ::createExportCustomObjectsUsingPOST
     */
    public function testCreateExportCustomObjectsUsingPOST(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'createExportCustomObjectsUsingPOST'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideEnqueueExportCustomObjectsUsingPOST(): \Generator
    {
        yield from static::provideFakeRequests(
            200,
            [
                'string',
                'string',
            ],
            '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @dataProvider provideEnqueueExportCustomObjectsUsingPOST
     * @covers ::enqueueExportCustomObjectsUsingPOST
     */
    public function testEnqueueExportCustomObjectsUsingPOST(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'enqueueExportCustomObjectsUsingPOST'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideGetExportCustomObjectsFileUsingGET(): \Generator
    {
        yield from static::provideFakeRequests(
            200,
            [
                'string',
                'string',
                'string',
            ],
            'object',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @dataProvider provideGetExportCustomObjectsFileUsingGET
     * @covers ::getExportCustomObjectsFileUsingGET
     */
    public function testGetExportCustomObjectsFileUsingGET(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== 'object') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'getExportCustomObjectsFileUsingGET'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideGetExportCustomObjectsStatusUsingGET(): \Generator
    {
        yield from static::provideFakeRequests(
            200,
            [
                'string',
                'string',
            ],
            '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                'string',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @dataProvider provideGetExportCustomObjectsStatusUsingGET
     * @covers ::getExportCustomObjectsStatusUsingGET
     */
    public function testGetExportCustomObjectsStatusUsingGET(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponse') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'getExportCustomObjectsStatusUsingGET'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }

    public static function provideGetExportCustomObjectsUsingGET(): \Generator
    {
        yield from static::provideFakeRequests(
            200,
            [
                'string',
                'string[]',
                'int',
                'string',
            ],
            '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken',
            ['application/json']
        );
        yield from static::provideFakeRequests(
            299,
            [
                'string',
                'string[]',
                'int',
                'string',
            ],
            null,
            ['application/json']
        );
        yield from static::provideFakeRequests(
            499,
            [
                'string',
                'string[]',
                'int',
                'string',
            ],
            null,
            ['application/json']
        );
    }

    /**
     * @dataProvider provideGetExportCustomObjectsUsingGET
     * @covers ::getExportCustomObjectsUsingGET
     */
    public function testGetExportCustomObjectsUsingGET(
        int $code,
        array $params,
        $data,
        bool $rt,
        string $content_type,
        array $args
    ): void {
        if ($code <= 299 && $args[2] !== '\NecLimDul\MarketoRest\Lead\Model\ResponseOfExportResponseWithToken') {
            $this->markTestSkipped('Multiple return types do not really work...');
        }
        $sot = $this->sot;
        $c = fn() => call_user_func_array([$sot, 'getExportCustomObjectsUsingGET'], $params);
        $this->assertApiRequest($c, $data, $code, $rt, $content_type);
    }
}
