name: PHP Composer

on:
  push:
    branches: [ main, '2.0', '3.0', '4.0' ]
  pull_request:
    branches: [ main, '2.0', '3.0', '4.0' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Run static analysis
        run: composer static
  cs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup
      - name: Run style check
        run: composer phpcs

  test:
    needs: [lint, cs]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup
      - name: Run test suite
        uses: php-actions/phpunit@v4
        with:
          memory_limit: 256M
